/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface AffelnetFormation {
  /**
   * Clé unique de la formation (pour envoi aux ministères éducatifs)
   */
  cle_ministere_educatif?: string | null;
  /**
   * code côté affelnet, unique par académie, de la formation
   */
  code_offre?: string | null;
  /**
   * uai de l'établissement de formation
   */
  uai?: string | null;
  /**
   * uai de l'établissement responsable
   */
  uai_responsable?: string | null;
  /**
   * uai de l'établissement formateur
   */
  uai_formateur?: string | null;
  /**
   * libellé du type de l'établissement (centre de formation d'apprentis, lycée, etc..) de formation
   */
  libelle_type_etablissement?: string | null;
  /**
   * libellé nom de l'établissement de formation
   */
  libelle_etablissement?: string | null;
  /**
   * numéro et adresse de l'établissement de formation
   */
  adresse?: string | null;
  /**
   * code postal de l'établissement de formation
   */
  code_postal?: string | null;
  /**
   * commune de l'établissement de formation
   */
  commune?: string | null;
  /**
   * Téléphone de l'établissement de formation
   */
  telephone?: string | null;
  /**
   * email de l'établissement de formation
   */
  email?: string | null;
  /**
   * nom de l'academie de l'établissement de formation
   */
  academie?: string | null;
  /**
   * ministère auquel est rattaché l'établissement de formation
   */
  ministere?: string | null;
  /**
   * type d'établissement (Privée / Public)
   */
  etablissement_type?: string | null;
  /**
   * type de contrat pris en charge par l'établissement de formation
   */
  type_contrat?: string | null;
  /**
   * code du type de l'établissement de formation
   */
  code_type_etablissement?: string | null;
  /**
   * code nature de l'établissement de formation
   */
  code_nature?: string | null;
  /**
   * code district de l'établissement de formation
   */
  code_district?: string | null;
  /**
   * code bassin de l'établissement de formation
   */
  code_bassin?: string | null;
  /**
   * code cio
   */
  cio?: string | null;
  /**
   * l'établissement propose un internat
   */
  internat?: boolean | null;
  /**
   * L'établissement fait partie du réseau ambition réussite
   */
  reseau_ambition_reussite?: boolean | null;
  /**
   * libellé mnémonique de la formation
   */
  libelle_mnemonique?: string | null;
  /**
   * code spécialité de la formation
   */
  code_specialite?: string | null;
  /**
   * libellé BAN de la formation
   */
  libelle_ban?: string | null;
  /**
   * code MEF de la formation
   */
  code_mef?: string | null;
  /**
   * code voie de la formation
   */
  code_voie?: string | null;
  /**
   * type de voie de la formation
   */
  type_voie?: string | null;
  /**
   * saisie possible depuis la 3ème année de collège
   */
  saisie_possible_3eme?: boolean | null;
  /**
   * saisie reservé au filière SEGPA
   */
  saisie_reservee_segpa?: boolean | null;
  /**
   * saisie possible depuis la 2nde (1ère année de lycée)
   */
  saisie_possible_2nde?: boolean | null;
  /**
   * formation affiché dans le TSA
   */
  visible_tsa?: boolean | null;
  /**
   * libellé affiché dans le sa
   */
  libelle_formation?: string | null;
  /**
   * url description formation onisep
   */
  url_onisep_formation?: string | null;
  /**
   * Libellé long de l'établissement délivrant la formation
   */
  libelle_etablissement_tsa?: string | null;
  /**
   * url description établissement onisep
   */
  url_onisep_etablissement?: string | null;
  /**
   * ville de l'établissement
   */
  ville?: string | null;
  /**
   * campus métier
   */
  campus_metier?: boolean | null;
  /**
   * condition particulière
   */
  modalites?: boolean | null;
  /**
   * coordonnées latitude de l'établissement
   */
  coordonnees_gps_latitude?: string | null;
  /**
   * coordonnées longitude de l'établissement
   */
  coordonnees_gps_longitude?: string | null;
  /**
   * Informations de la formation
   */
  informations?: string | null;
  /**
   * Siret du gestionnaire
   */
  siret_uai_gestionnaire?: string | null;
  /**
   * Est-ce que la formation a été intégrée dans Affelnet via le catalogue ou manuellement
   */
  integree_catalogue?: boolean | null;
  /**
   * tableau des matching des formations catalogue
   */
  matching_mna_formation?: unknown[];
  /**
   * force du matching
   */
  matching_type?: string | null;
  _id?: Types.ObjectId;
  updated_at?: Date;
  created_at?: Date;
}
