/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface ConsoleStat {
  /**
   * Plateforme de destination
   */
  plateforme: "affelnet" | "parcoursup";
  /**
   * Date de la statistique
   */
  date: Date;
  /**
   * Nombre de formations publiées à cette date et vers cette plateforme
   */
  formations_publiees: number;
  /**
   * Nombre de formations intégrables à cette date et vers cette plateforme
   */
  formations_integrables: number;
  /**
   * Nombre d'organismes avec des formations publiées à cette date et vers cette plateforme
   */
  organismes_avec_formations_publiees: number;
  /**
   * Nombre d'organismes avec des formations intégrables à cette date et vers cette plateforme
   */
  organismes_avec_formations_integrables: number;
  _id?: Types.ObjectId;
}
