/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface Consumption {
  /**
   * Chemin d'appel
   */
  path?: string;
  /**
   * Method d'appel
   */
  method?: string;
  /**
   * Nombre d'appels de la route
   */
  globalCallCount?: number;
  /**
   * Consommateur de l'api
   */
  consumers?: ItemOfConsumers[];
  _id?: Types.ObjectId;
}
export interface ItemOfConsumers {
  caller?: string;
  callCount?: number;
  date?: Date;
}
