/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface ConsoleStat {
  /**
   * Plateforme de destination
   */
  plateforme: "affelnet" | "parcoursup";
  /**
   * Date de la statistique
   */
  date: Date;
  /**
   * Statistiques propre à chaque académie, ainsi qu'à toute la France
   */
  stats?: ItemOfStats[];
  "Toute la France"?: TouteLaFrance;
  Lyon?: Lyon;
  Montpellier?: Montpellier;
  "Nancy-Metz"?: NancyMetz;
  Poitiers?: Poitiers;
  Rennes?: Rennes;
  Strasbourg?: Strasbourg;
  Toulouse?: Toulouse;
  Nantes?: Nantes;
  "Orléans-Tours"?: OrleansTours;
  Reims?: Reims;
  Amiens?: Amiens;
  Limoges?: Limoges;
  Nice?: Nice;
  Créteil?: Creteil;
  Versailles?: Versailles;
  Corse?: Corse;
  "La Réunion"?: LaReunion;
  Martinique?: Martinique;
  Guadeloupe?: Guadeloupe;
  Guyane?: Guyane;
  Mayotte?: Mayotte;
  Normandie?: Normandie;
  Paris?: Paris;
  "Aix-Marseille"?: AixMarseille;
  Besançon?: Besancon;
  Bordeaux?: Bordeaux;
  "Clermont-Ferrand"?: ClermontFerrand;
  Dijon?: Dijon;
  Grenoble?: Grenoble;
  Lille?: Lille;
  _id?: Types.ObjectId;
}
export interface ItemOfStats {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface TouteLaFrance {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Lyon {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Montpellier {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface NancyMetz {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Poitiers {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Rennes {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Strasbourg {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Toulouse {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Nantes {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface OrleansTours {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Reims {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Amiens {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Limoges {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Nice {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Creteil {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Versailles {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Corse {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface LaReunion {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Martinique {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Guadeloupe {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Guyane {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Mayotte {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Normandie {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Paris {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface AixMarseille {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Besancon {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Bordeaux {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface ClermontFerrand {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Dijon {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Grenoble {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface Lille {
  academie?: string;
  formations_publiees?: number;
  formations_integrables?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_integrables?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
