/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConsumptionSchema {
  /**
   * Chemin d'appel
   */
  path?: string;
  /**
   * Method d'appel
   */
  method?: string;
  /**
   * Nombre d'appels de la route
   */
  globalCallCount?: number;
  /**
   * Consommateur de l'api
   */
  consumers?: ItemOfConsumers[];
  _id?: string;
}
export interface ItemOfConsumers {
  caller?: string;
  callCount?: number;
  date?: Date;
}
