/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface DualControlPerimeterReport {
  /**
   * Plateforme de destination
   */
  plateforme: "affelnet" | "parcoursup";
  /**
   * Date du rapport
   */
  date: Date;
  /**
   * Liste des statuts avec le nombre de formations correspondant
   */
  statuts?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
