/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface DualControlReport {
  /**
   * Un discriminant à des fin de filtrage des rapports
   */
  discriminator?: string;
  /**
   * Date du rapport
   */
  date: Date;
  /**
   * Nombre total de formations dans le catalogue
   */
  totalFormation: number;
  /**
   * Nombre total de formations dans le nouveau flux
   */
  totalDualControlFormation: number;
  /**
   * Nombre total de formations dans le catalogue, incluant les non-publiées
   */
  totalFormationWithUnpublished: number;
  /**
   * Nombre total de formations dans le nouveau flux, incluant les non-publiées
   */
  totalDualControlFormationWithUnpublished: number;
  /**
   * Nombre de formations dans le nouveau flux qui n'existe pas dans le catalogue
   */
  totalNotFound?: number;
  /**
   * Liste des champs avec le nombre d'écarts constatés par champ (clé: valeur)
   */
  fields?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
