/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

/**
 * Détails RNCP (bloc de compétences etc..)
 */
export type RncpDetails = {
  /**
   * Date de validité de la fiche
   */
  date_fin_validite_enregistrement?: Date;
  /**
   * fiche active ou non
   */
  active_inactive?: string | null;
  /**
   * état fiche ex: Publiée
   */
  etat_fiche_rncp?: string | null;
  /**
   * Niveau européen ex: niveauu5
   */
  niveau_europe?: string | null;
  /**
   * Code type de certification (ex: DE)
   */
  code_type_certif?: string | null;
  /**
   * Type de certification (ex: diplôme d'état)
   */
  type_certif?: string | null;
  /**
   * Code rncp de l'ancienne fiche
   */
  ancienne_fiche?: string[] | null;
  /**
   * Code rncp de la nouvelle fiche
   */
  nouvelle_fiche?: string[] | null;
  /**
   * Demande en cours de d'habilitation
   */
  demande?: number;
  /**
   * Certificateurs
   */
  certificateurs?: ItemOfCertificateurs[];
  /**
   * Code NSF
   */
  nsf_code?: string | null;
  /**
   * Libellé NSF
   */
  nsf_libelle?: string | null;
  /**
   * Romes
   */
  romes?: ItemOfRomes[];
  /**
   * Blocs de compétences
   */
  blocs_competences?: {
    [k: string]: unknown;
  }[];
  /**
   * Voix d'accès
   */
  voix_acces?: {
    [k: string]: unknown;
  }[];
  /**
   * Partenaires
   */
  partenaires?: ItemOfPartenaires[];
  /**
   * Code rncp périmé (date fin enregistrement avant le 31 aout de l'année courante)
   */
  rncp_outdated?: boolean;
  /**
   * Type d'enregistrement (issue de FranceCompétences)
   */
  type_enregistrement?: string | null;
} | null;
/**
 * Cause du rejet de publication
 */
export type Rejection = {
  /**
   * L'erreur telle que retournée par la plateforme
   */
  error?: string | null;
  /**
   * La description textuelle de l'erreur retournée
   */
  description?: string | null;
  /**
   * L'action à mener pour résoudre le rejet.
   */
  action?: string | null;
  /**
   * Adresse email de la personne ayant pris en charge le rejet de publication
   */
  handled_by?: string | null;
  /**
   * Date à laquelle le rejet de publication a été pris en charge
   */
  handled_date?: Date;
} | null;
/**
 * Données pour étude France Compétence
 */
export type FranceCompetenceInfos = {
  fc_is_catalog_general?: boolean;
  fc_is_habilite_rncp?: boolean;
  fc_is_certificateur?: boolean;
  fc_is_certificateur_siren?: boolean;
  fc_is_partenaire?: boolean;
  fc_has_partenaire?: boolean;
} | null;
/**
 * Statut parcoursup
 */
export type ParcoursupStatutReinitialisation = {
  /**
   * Utilisateur ayant effectué la réinitialisation
   */
  user?: string | null;
  /**
   * Date à laquelle la réinitialisation a été effectuée
   */
  date?: Date;
  /**
   * Motif de la réinitialisation
   */
  comment?: string | null;
} | null;

export interface Formation {
  /**
   * Clé unique de la formation (pour envoi aux ministères éducatifs)
   */
  cle_ministere_educatif?: string | null;
  /**
   * Code formation diplôme (education nationale)
   */
  cfd?: string | null;
  /**
   * Lettre spécialité du code cfd
   */
  cfd_specialite?: {
    [k: string]: unknown;
  } | null;
  /**
   * BCN : cfd périmé (fermeture avant le 31 août de l'année courante)
   */
  cfd_outdated?: boolean;
  /**
   * Date de fermeture du cfd
   */
  cfd_date_fermeture?: Date;
  /**
   * Code formation diplôme d'entrée (année 1 de l'apprentissage)
   */
  cfd_entree?: string | null;
  /**
   * Date de fermeture du cfd
   */
  cfd_entree_date_fermeture?: Date;
  /**
   * Nom de l'académie
   */
  nom_academie?: string | null;
  /**
   * Numéro de l'académie
   */
  num_academie?: string;
  /**
   * Code postal
   */
  code_postal?: string | null;
  /**
   * Code commune INSEE
   */
  code_commune_insee?: string | null;
  /**
   * Numéro de département
   */
  num_departement?: string | null;
  /**
   * Nom du département
   */
  nom_departement?: string | null;
  /**
   * Numéro de département
   */
  region?: string | null;
  /**
   * Localité
   */
  localite?: string | null;
  /**
   * UAI du lieu de la formation
   */
  uai_formation?: string | null;
  /**
   * L'UAI du lieu de formation est il valide ?
   */
  uai_formation_valide?: boolean | null;
  /**
   * Nom de la formation déclaratif
   */
  nom?: string | null;
  /**
   * Intitulé comme transmis par RCO
   */
  intitule_rco?: string | null;
  /**
   * Intitulé long de la formation normalisé BCN
   */
  intitule_long?: string | null;
  /**
   * Intitulé court de la formation normalisé BCN
   */
  intitule_court?: string | null;
  /**
   * Diplôme ou titre visé
   */
  diplome?: string | null;
  /**
   * Niveau de la formation
   */
  niveau?: string | null;
  /**
   * Url de redirection vers le site de l'ONISEP
   */
  onisep_url?: string | null;
  /**
   * Intitulé éditorial l'ONISEP
   */
  onisep_intitule?: string | null;
  /**
   * Libellé poursuite étude l'ONISEP (séparateur ;)
   */
  onisep_libelle_poursuite?: string | null;
  /**
   * Lien vers site de l'ONISEP api
   */
  onisep_lien_site_onisepfr?: string | null;
  /**
   * Disciplines ONISEP (séparateur ;)
   */
  onisep_discipline?: string | null;
  /**
   * Domaine et sous domaine ONISEP (séparateur ;)
   */
  onisep_domaine_sousdomaine?: string | null;
  /**
   * Code RNCP
   */
  rncp_code?: string | null;
  /**
   * Intitulé du code RNCP
   */
  rncp_intitule?: string | null;
  /**
   * Le titre RNCP est éligible en apprentissage
   */
  rncp_eligible_apprentissage?: boolean;
  rncp_details?: RncpDetails;
  /**
   * Codes ROME
   */
  rome_codes?: string[];
  /**
   * Périodes de début de la formation
   */
  periode?: Date[];
  /**
   * Capacité d'accueil
   */
  capacite?: string | null;
  /**
   * Durée de la formation en années
   */
  duree?: string | null;
  /**
   * Durée incohérente avec les codes mefs
   */
  duree_incoherente?: boolean | null;
  /**
   * Année de la formation (cursus)
   */
  annee?: string | null;
  /**
   * Année incohérente avec les codes mefs
   */
  annee_incoherente?: boolean | null;
  rejection?: Rejection;
  /**
   * Date de dernière modification du statut Affelnet ou Parcoursup
   */
  last_statut_update_date?: Date;
  /**
   * Est publiée, la formation est éligible pour le catalogue
   */
  published?: boolean;
  /**
   * La publication vers les plateformes est forcée (contournement catalogue non-éligible dans certains cas)
   */
  forced_published?: boolean;
  /**
   * Historique des mises à jours
   */
  updates_history?: ItemOfUpdatesHistory[];
  /**
   * Date de dernières mise à jour
   */
  last_update_at?: Date;
  /**
   * Qui a réalisé la dernière modification
   */
  last_update_who?: string | null;
  /**
   * Latitude et longitude du lieu de formation
   */
  lieu_formation_geo_coordonnees?: string;
  /**
   * Latitude et longitude du lieu de formation déduit de l'adresse du flux RCO
   */
  lieu_formation_geo_coordonnees_computed?: string;
  /**
   * Distance entre les coordonnées transmises et déduites à partir de l'adresse
   */
  distance?: number | null;
  /**
   * Adresse du lieu de formation
   */
  lieu_formation_adresse?: string | null;
  /**
   * Adresse du lieu de formation déduit de la géolocalisation du flux RCO
   */
  lieu_formation_adresse_computed?: string | null;
  /**
   * Siret du lieu de formation
   */
  lieu_formation_siret?: string | null;
  /**
   * **[DEPRECATED]** Id de formation RCO (id_formation + id_action + id_certifinfo)
   */
  id_rco_formation?: string | null;
  /**
   * Identifiant de la formation
   */
  id_formation?: string | null;
  /**
   * Identifiant des actions concaténés
   */
  id_action?: string | null;
  /**
   * Identifiant des actions concaténés
   */
  ids_action?: string[];
  /**
   * Identifiant certifInfo (unicité de la certification)
   */
  id_certifinfo?: string | null;
  /**
   * Tableau de tags (2020, 2021, etc.)
   */
  tags?: string[];
  /**
   * BCN : libelle court fusion table n_formation_diplome ou v_formation_diplome
   */
  libelle_court?: string | null;
  /**
   * BCN : niveau formation diplôme
   */
  niveau_formation_diplome?: string | null;
  /**
   * BCN : Codes MEF 10 caractères
   */
  bcn_mefs_10?: ItemOfBcnMefs_10[];
  /**
   * Champs édités par un utilisateur
   */
  editedFields?: {
    [k: string]: unknown;
  } | null;
  /**
   * distance entre le Lieu de formation et l'établissement formateur
   */
  distance_lieu_formation_etablissement_formateur?: number | null;
  /**
   * Niveau d'entrée de l'apprenti minimum obligatoire pour cette formation
   */
  niveau_entree_obligatoire?: number | null;
  /**
   * Renseigné si la formation peut être suivie entièrement à distance
   */
  entierement_a_distance?: boolean;
  france_competence_infos?: FranceCompetenceInfos;
  /**
   * Formation éligible au catalogue générale
   */
  catalogue_published?: boolean;
  /**
   * Dates de début de session
   */
  date_debut?: Date[];
  /**
   * Dates de fin de session
   */
  date_fin?: Date[];
  /**
   * Session en entrée / sortie permanente
   */
  modalites_entrees_sorties?: boolean[];
  /**
   * Identifiant RCO
   */
  id_RCO?: string | null;
  /**
   * Partenaires
   */
  partenaires?: unknown[];
  /**
   * Objectif de la formation
   */
  objectif?: string | null;
  /**
   * Identifiant de la formation
   */
  contenu?: string | null;
  /**
   * Badge siret actif/inactif
   */
  siret_actif?: string | null;
  /**
   * Nouvelle fiche
   */
  nouvelle_fiche?: boolean;
  /**
   * Type d'enregistrement (issue de CertifInfo)
   */
  CI_inscrit_rncp?: string | null;
  /**
   * Est remplacée par la clé ME
   */
  cle_me_remplace_par?: string[] | null;
  /**
   * Remplace la clé ME
   */
  cle_me_remplace?: string[] | null;
  /**
   * La formation relève du ministère de l'agriculture
   */
  agriculture?: boolean | null;
  /**
   * Identifiant établissement gestionnaire
   */
  etablissement_gestionnaire_id?: string | null;
  /**
   * Numéro siret gestionnaire
   */
  etablissement_gestionnaire_siret?: string | null;
  /**
   * Enseigne établissement gestionnaire
   */
  etablissement_gestionnaire_enseigne?: string | null;
  /**
   * UAI de l'etablissement gestionnaire
   */
  etablissement_gestionnaire_uai?: string | null;
  /**
   * Etablissement gestionnaire est publié
   */
  etablissement_gestionnaire_published?: boolean;
  /**
   * Etablissement gestionnaire est habilité RNCP ou pas
   */
  etablissement_gestionnaire_habilite_rncp?: boolean;
  /**
   * Etablissement gestionnaire est certifié Qualité
   */
  etablissement_gestionnaire_certifie_qualite?: boolean;
  /**
   * Numéro et rue établissement gestionnaire
   */
  etablissement_gestionnaire_adresse?: string | null;
  /**
   * Code postal établissement gestionnaire
   */
  etablissement_gestionnaire_code_postal?: string | null;
  /**
   * Code commune insee établissement gestionnaire
   */
  etablissement_gestionnaire_code_commune_insee?: string | null;
  /**
   * Localité établissement gestionnaire
   */
  etablissement_gestionnaire_localite?: string | null;
  /**
   * Complément d'adresse de l'établissement gestionnaire
   */
  etablissement_gestionnaire_complement_adresse?: string | null;
  /**
   * Cedex
   */
  etablissement_gestionnaire_cedex?: string | null;
  /**
   * Raison sociale établissement gestionnaire
   */
  etablissement_gestionnaire_entreprise_raison_sociale?: string | null;
  /**
   * Latitude et longitude de l'établissement gestionnaire
   */
  geo_coordonnees_etablissement_gestionnaire?: string;
  /**
   * région gestionnaire
   */
  etablissement_gestionnaire_region?: string | null;
  /**
   * Numéro de departement gestionnaire
   */
  etablissement_gestionnaire_num_departement?: string | null;
  /**
   * Nom du departement gestionnaire
   */
  etablissement_gestionnaire_nom_departement?: string | null;
  /**
   * Nom de l'académie gestionnaire
   */
  etablissement_gestionnaire_nom_academie?: string | null;
  /**
   * Numéro de l'académie gestionnaire
   */
  etablissement_gestionnaire_num_academie?: string;
  /**
   * Numéro siren gestionnaire
   */
  etablissement_gestionnaire_siren?: string | null;
  /**
   * Numéro Déclaration gestionnaire
   */
  etablissement_gestionnaire_nda?: string | null;
  /**
   * Date de création de l'établissement
   */
  etablissement_gestionnaire_date_creation?: Date;
  /**
   * Adresse email de contact de l'établissement gestionnaire
   */
  etablissement_gestionnaire_courriel?: string | null;
  /**
   * SIRET actif ou inactif pour l'établissement gestionnaire
   */
  etablissement_gestionnaire_actif?: string | null;
  /**
   * Identifiant établissement formateur
   */
  etablissement_formateur_id?: string | null;
  /**
   * Numéro siret formateur
   */
  etablissement_formateur_siret?: string | null;
  /**
   * Enseigne établissement formateur
   */
  etablissement_formateur_enseigne?: string | null;
  /**
   * UAI de l'etablissement formateur
   */
  etablissement_formateur_uai?: string | null;
  /**
   * Etablissement formateur est publié
   */
  etablissement_formateur_published?: boolean;
  /**
   * Etablissement formateur est habilité RNCP ou pas
   */
  etablissement_formateur_habilite_rncp?: boolean;
  /**
   * Etablissement formateur est certifié Qualité
   */
  etablissement_formateur_certifie_qualite?: boolean;
  /**
   * Numéro et rue établissement formateur
   */
  etablissement_formateur_adresse?: string | null;
  /**
   * Code postal établissement formateur
   */
  etablissement_formateur_code_postal?: string | null;
  /**
   * Code commune insee établissement formateur
   */
  etablissement_formateur_code_commune_insee?: string | null;
  /**
   * Localité établissement formateur
   */
  etablissement_formateur_localite?: string | null;
  /**
   * Complément d'adresse de l'établissement
   */
  etablissement_formateur_complement_adresse?: string | null;
  /**
   * Cedex
   */
  etablissement_formateur_cedex?: string | null;
  /**
   * Raison sociale établissement formateur
   */
  etablissement_formateur_entreprise_raison_sociale?: string | null;
  /**
   * Latitude et longitude de l'établissement formateur
   */
  geo_coordonnees_etablissement_formateur?: string;
  /**
   * région formateur
   */
  etablissement_formateur_region?: string | null;
  /**
   * Numéro de departement formateur
   */
  etablissement_formateur_num_departement?: string | null;
  /**
   * Nom du departement formateur
   */
  etablissement_formateur_nom_departement?: string | null;
  /**
   * Nom de l'académie formateur
   */
  etablissement_formateur_nom_academie?: string | null;
  /**
   * Numéro de l'académie formateur
   */
  etablissement_formateur_num_academie?: string;
  /**
   * Numéro siren formateur
   */
  etablissement_formateur_siren?: string | null;
  /**
   * Numéro Déclaration formateur
   */
  etablissement_formateur_nda?: string | null;
  /**
   * Date de création de l'établissement
   */
  etablissement_formateur_date_creation?: Date;
  /**
   * Adresse email de contact de l'établissement formateur
   */
  etablissement_formateur_courriel?: string | null;
  /**
   * SIRET actif ou inactif pour l'établissement formateur
   */
  etablissement_formateur_actif?: string | null;
  /**
   * Etablissement reference est soit formateur soit le gestionnaire
   */
  etablissement_reference?: string | null;
  /**
   * Etablissement reference est publié
   */
  etablissement_reference_published?: boolean;
  /**
   * Etablissement reference est habilité RNCP ou pas
   */
  etablissement_reference_habilite_rncp?: boolean;
  /**
   * Etablissement reference est certifié Qualité
   */
  etablissement_reference_certifie_qualite?: boolean;
  /**
   * Date de création de l'établissement
   */
  etablissement_reference_date_creation?: Date;
  /**
   * Dans le périmètre parcoursup
   */
  parcoursup_perimetre?: boolean;
  /**
   * Possède une date de début durant la prochaine session Parcoursup
   */
  parcoursup_session?: boolean;
  /**
   * Possède une date de début durant la précédente session Parcoursup
   */
  parcoursup_previous_session?: boolean;
  /**
   * Statut parcoursup
   */
  parcoursup_statut?:
    | "non publiable en l'état"
    | "publié"
    | "non publié"
    | "à publier"
    | "en attente de publication"
    | "à publier (vérifier accès direct postbac)"
    | "à publier (soumis à validation Recteur)"
    | "à publier (sous condition habilitation)"
    | "rejet de publication"
    | "fermé";
  /**
   * Statut parcoursup à la fin de la précédente campagne
   */
  parcoursup_previous_statut?:
    | "non publiable en l'état"
    | "publié"
    | "non publié"
    | "à publier"
    | "en attente de publication"
    | "à publier (vérifier accès direct postbac)"
    | "à publier (soumis à validation Recteur)"
    | "à publier (sous condition habilitation)"
    | "rejet de publication"
    | "fermé";
  /**
   * Parcoursup : historique des statuts
   */
  parcoursup_statut_history?: unknown[];
  /**
   * Erreur lors de la création de la formation sur ParcourSup (via le WS)
   */
  parcoursup_error?: string | null;
  /**
   * identifiant Parcoursup de la formation (g_ta_cod)
   */
  parcoursup_id?: string | null;
  /**
   * Date de publication (passage au statut "publié")
   */
  parcoursup_published_date?: Date;
  /**
   * Date de la dernière tentative d'export vers Parcoursup
   */
  parcoursup_export_date?: Date;
  /**
   * Parcoursup : raison de dépublication
   */
  parcoursup_raison_depublication?: string | null;
  /**
   * Tableau de Code MEF 10 caractères et modalités (filtrés pour Parcoursup si applicable)
   */
  parcoursup_mefs_10?: ItemOfParcoursupMefs_10[];
  parcoursup_statut_reinitialisation?: ParcoursupStatutReinitialisation;
  /**
   * Parcoursup : publication auto
   */
  parcoursup_publication_auto?: boolean | null;
  /**
   * Parcoursup : visible
   */
  parcoursup_perimetre_prise_rdv?: boolean;
  /**
   * Dans le périmètre Affelnet
   */
  affelnet_perimetre?: boolean;
  /**
   * Possède une date de début durant la prochaine session Affelnet
   */
  affelnet_session?: boolean;
  /**
   * Possède une date de début durant la précédente session Affelnet
   */
  affelnet_previous_session?: boolean;
  /**
   * Statut affelnet
   */
  affelnet_statut?:
    | "non publiable en l'état"
    | "publié"
    | "non publié"
    | "à publier"
    | "en attente de publication"
    | "à publier (soumis à validation)";
  /**
   * Statut affelnet à la fin de la précédente campagne
   */
  affelnet_previous_statut?:
    | "non publiable en l'état"
    | "publié"
    | "non publié"
    | "à publier"
    | "en attente de publication"
    | "à publier (soumis à validation)";
  /**
   * Affelnet : historique des statuts
   */
  affelnet_statut_history?: unknown[];
  /**
   * identifiant Affelnet de la formation (code vœu)
   */
  affelnet_id?: string | null;
  /**
   * Date de publication (passage au statut "publié")
   */
  affelnet_published_date?: Date;
  /**
   * Affelnet : Informations offre de formation
   */
  affelnet_infos_offre?: string | null;
  /**
   * Affelnet : Libellé ressource complémentaire
   */
  affelnet_url_infos_offre?: string | null;
  /**
   * Affelnet : Modalités particulières
   */
  affelnet_modalites_offre?: string | null;
  /**
   * Affelnet : Lien vers la ressource
   */
  affelnet_url_modalites_offre?: string | null;
  /**
   * Affelnet : code nature de l'établissement de formation
   */
  affelnet_code_nature?: string | null;
  /**
   * Affelnet : type d'établissement (PR: Privé / PU: Public)
   */
  affelnet_secteur?: "PR" | "PU" | null;
  /**
   * Affelnet : raison de dépublication
   */
  affelnet_raison_depublication?: string | null;
  /**
   * Tableau de Code MEF 10 caractères et modalités (filtrés pour Affelnet si applicable)
   */
  affelnet_mefs_10?: ItemOfAffelnetMefs_10[];
  /**
   * Affelnet : publication auto
   */
  affelnet_publication_auto?: boolean | null;
  /**
   * Affelnet : visible
   */
  affelnet_perimetre_prise_rdv?: boolean;
  _id?: Types.ObjectId;
  updated_at?: Date;
  created_at?: Date;
}
export interface ItemOfCertificateurs {
  certificateur?: string;
  siret_certificateur?: string;
}
export interface ItemOfRomes {
  rome?: string;
  libelle?: string;
}
export interface ItemOfPartenaires {
  Nom_Partenaire?: string;
  Siret_Partenaire?: string;
  Habilitation_Partenaire?: string;
}
export interface ItemOfUpdatesHistory {
  /**
   * Valeurs avant mise à jour
   */
  from?: {
    [k: string]: unknown;
  };
  /**
   * Valeurs après mise à jour
   */
  to?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
export interface ItemOfBcnMefs_10 {
  mef10?: string;
  modalite?: Modalite;
  date_fermeture?: Date;
  _id?: Types.ObjectId;
}
export interface Modalite {
  duree?: string;
  annee?: string;
}
export interface ItemOfParcoursupMefs_10 {
  mef10?: string;
  modalite?: Modalite1;
  date_fermeture?: Date;
  _id?: Types.ObjectId;
}
export interface Modalite1 {
  duree?: string;
  annee?: string;
}
export interface ItemOfAffelnetMefs_10 {
  mef10?: string;
  modalite?: Modalite2;
  date_fermeture?: Date;
  _id?: Types.ObjectId;
}
export interface Modalite2 {
  duree?: string;
  annee?: string;
}
