/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface ParcoursupFormation {
  /**
   * Uai gestionnaire de l'établissement
   */
  uai_gestionnaire?: string;
  /**
   * Uai composante de l'établissement
   */
  uai_composante?: string;
  /**
   * Uai affilié de l'établissement
   */
  uai_affilie?: string;
  /**
   * Libellé de l'uai composante
   */
  libelle_uai_composante?: string;
  /**
   * Libellé de l'uai affilié
   */
  libelle_uai_affilie?: string;
  /**
   * Code commune  de l'établissement
   */
  code_commune_insee?: string;
  /**
   * Libellé de la commune
   */
  libelle_commune?: string;
  /**
   * Code postal de l'établissement
   */
  code_postal?: string;
  /**
   * Nom de l'académie référente de l'établissement
   */
  nom_academie?: string;
  /**
   * Code du ministère responsable rattaché à l'établissement
   */
  code_ministere?: string;
  /**
   * Code du ministère responsable rattaché à l'établissement
   */
  libelle_ministere?: string;
  /**
   * Type d'établissement délivrant la formation
   */
  type_etablissement?: string;
  /**
   * Code de la formation
   */
  code_formation?: string;
  /**
   * Libelle de la formation
   */
  libelle_formation?: string;
  /**
   * Code de la spécialité
   */
  code_specialite?: string;
  /**
   * Libelle de la spécialité
   */
  libelle_specialite?: string;
  /**
   * Code de la formation à laquelle la spécialité est rattaché
   */
  code_formation_initiale?: string;
  /**
   * Code MEF de la formation
   */
  code_mef_10?: string;
  /**
   * Code formation diplome de la formation
   */
  code_cfd?: string;
  /**
   * Code formation diplome extra de la formation
   */
  code_cfd_2?: string;
  /**
   * Code formation diplome extra de la formation
   */
  code_cfd_3?: string;
  /**
   * Force du matching avec le catalogue des formations
   */
  matching_type?: string;
  /**
   * Formations du catalogue matchant la formation parcoursup
   */
  matching_mna_formation?: string & unknown[];
  /**
   * Etablissement du catalogue matchant les formation présente dans matching_mna_formation
   */
  matching_mna_etablissement?: string & unknown[];
  /**
   * Statuts ParcourSup MNA module de perimetre
   */
  matching_mna_parcoursup_statuts?: string[];
  /**
   * Etat de la réconciliation de la formation
   */
  etat_reconciliation?: boolean;
  /**
   * Statut
   */
  statut_reconciliation?: "AUTOMATIQUE" | "VALIDE" | "REJETE" | "INCONNU" | "A_VERIFIER";
  /**
   * Identifiant formation mna validés
   */
  validated_formation_ids?: string[];
  /**
   * Si la formation Précédemment Rejeté a été mise à jour
   */
  matching_rejete_updated?: boolean;
  /**
   *  raison de dépublication
   */
  matching_rejete_raison?: string;
  /**
   * Tableau des raisons de rejet
   */
  rapprochement_rejete_raisons?: string[];
  /**
   * Details raison autre rejet
   */
  rapprochement_rejete_raison_autre?: string;
  /**
   * identifiant unique de la formation côté parcoursup (CODEFORMATIONINSCRIPTION)
   */
  id_parcoursup?: string;
  /**
   * uai renseigné sur la fiche CERFA
   */
  uai_cerfa?: string;
  /**
   * uai insert jeune
   */
  uai_insert_jeune?: string;
  /**
   * uai
   */
  uai_map?: string;
  /**
   * siret renseigné sur la fiche CERFA
   */
  siret_cerfa?: string;
  /**
   * siret
   */
  siret_map?: string;
  /**
   * cfd map
   */
  codediplome_map?: string;
  /**
   * CODEFORMATIONINSCRIPTION
   */
  code_formation_inscription?: string;
  /**
   * CODEFORMATIONACCUEIL
   */
  code_formation_accueil?: string;
  /**
   * LATITUDE
   */
  latitude?: string;
  /**
   * LONGITUDE
   */
  longitude?: string;
  /**
   * COMPLEMENTADRESSE
   */
  complement_adresse?: string;
  /**
   * COMPLEMENTADRESSE1
   */
  complement_adresse_1?: string;
  /**
   * COMPLEMENTADRESSE2
   */
  complement_adresse_2?: string;
  /**
   * COMPLEMENTCODEPOSTAL
   */
  complement_code_postal?: string;
  /**
   * COMPLEMENTCOMMUNE
   */
  complement_commune?: string;
  /**
   * LIB_INS
   */
  libelle_insert_jeune?: string;
  /**
   * COMPLEMENTCEDEX
   */
  complement_cedex?: string;
  /**
   * PREMIERELIGNEADRESSEETAB
   */
  adresse_etablissement_l1?: string;
  /**
   * SECONDELIGNEADRESSEETAB
   */
  adresse_etablissement_l2?: string;
  /**
   * CODE_CFD_MNA
   */
  codes_cfd_mna?: string & string[];
  /**
   * CODE_RNCP_MNA
   */
  codes_rncp_mna?: string & string[];
  /**
   * CODE_ROMES_MNA
   */
  codes_romes_mna?: string & string[];
  /**
   * TYPE_RAPPROCHEMENT_MNA
   */
  type_rapprochement_mna?: string;
  /**
   * vaut true si aucune formation publiée dans le catalogue ne correspond (utile pour les VALIDE & REJETE)
   */
  is_orphan?: boolean;
  _id?: Types.ObjectId;
}
