/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface ParcoursupFormationCheck {
  /**
   * UAI_GES
   */
  uai_ges?: string | null;
  /**
   * UAI_COMPOSANTE
   */
  uai_composante?: string | null;
  /**
   * LIB_COMPOSANTE
   */
  lib_composante?: string | null;
  /**
   * LIB_INS
   */
  lib_ins?: string | null;
  /**
   * UAI_AFF
   */
  uai_aff?: string | null;
  /**
   * LIB_AFF
   */
  lib_aff?: string | null;
  /**
   * CODECOMMUNE
   */
  codecommune?: string | null;
  /**
   * LIBCOMMUNE
   */
  libcommune?: string | null;
  /**
   * CODEPOSTAL
   */
  codepostal?: string | null;
  /**
   * ACADÉMIE
   */
  académie?: string | null;
  /**
   * MINISTERETUTELLE
   */
  ministeretutelle?: string | null;
  /**
   * LIBMINISTERE
   */
  libministere?: string | null;
  /**
   * TYPEETA
   */
  typeeta?: string | null;
  /**
   * CODEFORMATION
   */
  codeformation?: string | null;
  /**
   * LIBFORMATION
   */
  libformation?: string | null;
  /**
   * CODESPÉCIALITÉ
   */
  codespécialité?: string | null;
  /**
   * LIBSPÉCIALITÉ
   */
  libspécialité?: string | null;
  /**
   * CODESPÉFORMATIONINITIALE
   */
  codespéformationinitiale?: string | null;
  /**
   * CODEMEF
   */
  codemef?: string | null;
  /**
   * UAI_INSERT
   */
  uai_insert?: string | null;
  /**
   * UAI_CERFA
   */
  uai_cerfa?: string | null;
  /**
   * SIRET_CERFA
   */
  siret_cerfa?: string | null;
  /**
   * UAI_MAP
   */
  uai_map?: string | null;
  /**
   * SIRET_MAP
   */
  siret_map?: string | null;
  /**
   * CODEDIPLOME_MAP
   */
  codediplome_map?: string | null;
  /**
   * CODEFORMATIONINSCRIPTION (id_parcoursup)
   */
  codeformationinscription?: string | null;
  /**
   * CODEFORMATIONACCUEIL
   */
  codeformationaccueil?: string | null;
  /**
   * LATITUDE
   */
  latitude?: string | null;
  /**
   * LONGITUDE
   */
  longitude?: string | null;
  /**
   * COMPLEMENTADRESSE
   */
  complementadresse?: string | null;
  /**
   * COMPLEMENTADRESSE1
   */
  complementadresse1?: string | null;
  /**
   * COMPLEMENTADRESSE2
   */
  complementadresse2?: string | null;
  /**
   * COMPLEMENTCODEPOSTAL
   */
  complementcodepostal?: string | null;
  /**
   * COMPLEMENTCOMMUNE
   */
  complementcommune?: string | null;
  /**
   * COMPLEMENTCEDEX
   */
  complementcedex?: string | null;
  /**
   * PREMIERELIGNEADRESSEETAB
   */
  premiereligneadresseetab?: string | null;
  /**
   * SECONDELIGNEADRESSEETAB
   */
  secondeligneadresseetab?: string | null;
  /**
   * ID_RCO (cle_ministere_educatif)
   */
  id_rco?: string | null;
  /**
   * FLAG_CERTIF
   */
  flag_certif?: string | null;
  _id?: Types.ObjectId;
}
