/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface PreviousSeasonFormationStat {
  /**
   * Plateforme pour laquelle la formation était dans le périmètre
   */
  plateforme: "affelnet" | "parcoursup";
  /**
   * Date de la statistique
   */
  date: Date;
  academie?: string;
  closed?: number;
  qualiopi_lost?: number;
  not_updated?: number;
  other?: number;
  _id?: Types.ObjectId;
}
