/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface PreviousSeasonFormation {
  /**
   * Clé unique de la formation (pour envoi aux ministères éducatifs)
   */
  cle_ministere_educatif: string;
  /**
   * Numéro de l'académie
   */
  num_academie: string;
  /**
   * Dans le périmètre parcoursup
   */
  parcoursup_perimetre?: boolean;
  /**
   * A eu une session parcoursup
   */
  parcoursup_session?: boolean;
  /**
   * Statut parcoursup
   */
  parcoursup_statut?:
    | "non publiable en l'état"
    | "publié"
    | "non publié"
    | "à publier"
    | "en attente de publication"
    | "à publier (vérifier accès direct postbac)"
    | "à publier (soumis à validation Recteur)"
    | "à publier (sous condition habilitation)"
    | "rejet de publication"
    | "fermé";
  /**
   * Dans le périmètre affelnet
   */
  affelnet_perimetre?: boolean;
  /**
   * A eu une session affelnet
   */
  affelnet_session?: boolean;
  /**
   * Statut affelnet
   */
  affelnet_statut?:
    | "non publiable en l'état"
    | "publié"
    | "non publié"
    | "à publier"
    | "en attente de publication"
    | "à publier (soumis à validation)";
  _id?: Types.ObjectId;
}
