/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface PreviousSeasonFormation {
  /**
   * Clé unique de la formation (pour envoi aux ministères éducatifs)
   */
  cle_ministere_educatif: string;
  /**
   * Numéro de l'académie
   */
  num_academie: string;
  /**
   * Plateforme pour laquelle la formation était dans le périmètre
   */
  plateforme: "affelnet" | "parcoursup";
  _id?: Types.ObjectId;
}
