/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RcoFormationSchema {
  /**
   * Clé unique de la formation (pour envoi aux ministères éducatifs)
   */
  cle_ministere_educatif?: string;
  /**
   * Identifiant de la formation
   */
  id_formation?: string;
  /**
   * Identifant des actions concaténés
   */
  id_action?: string;
  /**
   * Identifant certifInfo (unicité de la certification)
   */
  id_certifinfo?: string;
  /**
   * Numéro de siret de l'établissement gestionnaire
   */
  etablissement_gestionnaire_siret?: string;
  /**
   * Numéro d'UAI de l'établissement gestionnaire
   */
  etablissement_gestionnaire_uai?: string;
  /**
   * Adresse de l'établissement gestionnaire
   */
  etablissement_gestionnaire_adresse?: string;
  /**
   * Code postal de l'établissement gestionnaire
   */
  etablissement_gestionnaire_code_postal?: string;
  /**
   * Code commune Insee de l'établissement gestionnaire
   */
  etablissement_gestionnaire_code_insee?: string;
  /**
   * Latitude et longitude de l'établissement gestionnaire
   */
  etablissement_gestionnaire_geo_coordonnees?: string;
  /**
   * Numéro de siret de l'établissement formateur
   */
  etablissement_formateur_siret?: string;
  /**
   * Numéro d'UAI de l'établissement formateur
   */
  etablissement_formateur_uai?: string;
  /**
   * Adresse de l'établissement formateur
   */
  etablissement_formateur_adresse?: string;
  /**
   * Code postal de l'établissement formateur
   */
  etablissement_formateur_code_postal?: string;
  /**
   * Code commune Insee de l'établissement formateur
   */
  etablissement_formateur_code_insee?: string;
  /**
   * Latitude et longitude de l'établissement formateur
   */
  etablissement_formateur_geo_coordonnees?: string;
  /**
   * Numéro de siret du lieu de formation
   */
  etablissement_lieu_formation_siret?: string;
  /**
   * Numéro d'UAI du lieu de formation
   */
  etablissement_lieu_formation_uai?: string;
  /**
   * Adresse du lieu de formation
   */
  etablissement_lieu_formation_adresse?: string;
  /**
   * Code postal du lieu de formation
   */
  etablissement_lieu_formation_code_postal?: string;
  /**
   * Code commune Insee du lieu de formation
   */
  etablissement_lieu_formation_code_insee?: string;
  /**
   * Latitude et longitude du lieu de formation
   */
  etablissement_lieu_formation_geo_coordonnees?: string;
  /**
   * Code Formation Diplôme (education nationale)
   */
  cfd?: string;
  /**
   * Code RNCP
   */
  rncp_code?: string;
  /**
   * Capacité d'accueil
   */
  capacite?: string;
  /**
   * Périodes de début de la formation
   */
  periode?: string[];
  /**
   * Historique des mises à jours
   */
  updates_history?: unknown[];
  /**
   * Est publiée
   */
  published?: boolean;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
  /**
   * Date de dernière mise à jour
   */
  last_update_at?: Date;
  /**
   * A été convertie en mna formation
   */
  converted_to_mna?: boolean;
  /**
   * Erreur lors de la conversion de la formation
   */
  conversion_error?: string;
  /**
   * Id de formation RCO (id_formation + id_action + id_certifinfo)
   */
  id_rco_formation?: string;
  /**
   * Niveau d'entrée de l'apprenti minimum obligatoire pour cette formation
   */
  niveau_entree_obligatoire?: string;
  /**
   * Renseigné si la formation peut être suivie entièrement à distance
   */
  entierement_a_distance?: string;
  /**
   * Adresse email de contact de l'établissement formateur
   */
  etablissement_formateur_courriel?: string;
  /**
   * Adresse email de contact de l'établissement gestionnaire
   */
  etablissement_gestionnaire_courriel?: string;
  /**
   * Intitule de la formation
   */
  intitule_formation?: string;
  /**
   * Parcours suivi sur 3 caractères : P00 (quand la question du parcours ne se pose pas), sinon  P01, P02 et Pnt – tant que les sessions ne sont pas expertisées
   */
  parcours?: string;
  /**
   * Durée de la formation en années (1 à 5, X si en cours de collecte)
   */
  duree?: string;
  /**
   * Année d'entrée en apprentissage (1 à 5, X si en cours de collecte)
   */
  entree_apprentissage?: string;
  _id?: string;
}
