/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReglePerimetreSchema {
  /**
   * Plateforme pour laquelle s'applique la règle
   */
  plateforme: "affelnet" | "parcoursup";
  /**
   * Niveau sur lequel s'applique la règle
   */
  niveau: "3 (CAP...)" | "4 (BAC...)" | "5 (BTS, DEUST...)" | "6 (Licence, BUT...)" | "7 (Master, titre ingénieur...)";
  /**
   * Diplôme sur lequel s'applique la règle
   */
  diplome: string;
  /**
   * Statut appliqué quand la formation matche la règle
   */
  statut:
    | "hors périmètre"
    | "publié"
    | "non publié"
    | "à publier (sous condition habilitation)"
    | "à publier (vérifier accès direct postbac)"
    | "à publier (soumis à validation Recteur)"
    | "à publier (soumis à validation)"
    | "à publier"
    | "en attente de publication";
  /**
   * Académie pour laquelle la règle a été créé si il y en a une
   */
  num_academie?: number;
  /**
   * Les statuts à appliquer pour cette règle en académies
   */
  statut_academies?: {
    [k: string]: unknown;
  };
  /**
   * La règle pour matcher les formations (i.e: query mongo) qui s'ajoute au niveau + diplome (stringified)
   */
  regle_complementaire?: string;
  /**
   * La règle complémentaire, de type eS pour le rule builder
   */
  regle_complementaire_query?: string;
  /**
   * Nom du sous-ensemble
   */
  nom_regle_complementaire?: string;
  /**
   * En cas d'égalité sur la plateforme, niveau et diplome, priorité de la règle pour savoir laquelle est la plus forte
   */
  priorite?: number;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
  /**
   * Historique des mises à jours
   */
  updates_history?: unknown[];
  /**
   * Date de dernière mise à jour
   */
  last_update_at?: Date;
  /**
   * Qui a réalisé la dernière modification
   */
  last_update_who?: string;
  /**
   * True si la règle a été supprimée (soft delete)
   */
  is_deleted?: boolean;
  /**
   * Condition d'intégration dans la plateforme
   */
  condition_integration: "doit intégrer" | "peut intégrer" | "ne doit pas intégrer";
  /**
   * Durée en années pour matcher les formations
   */
  duree?: string;
  /**
   * Année d'inscription de la formation
   */
  annee?: string;
  _id?: string;
}
