/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReportSchema {
  /**
   * Type du rapport
   */
  type?: string;
  /**
   * Date du rapport
   */
  date?: Date;
  /**
   * Données du rapport
   */
  data?: {
    [k: string]: unknown;
  };
  /**
   * uuid across report
   */
  uuid?: string;
  _id?: string;
}
