/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface Report {
  /**
   * Type du rapport
   */
  type?: string;
  /**
   * Date du rapport
   */
  date?: Date;
  /**
   * Données du rapport
   */
  data?: {
    [k: string]: unknown;
  };
  /**
   * uuid across report
   */
  uuid?: string;
  _id?: Types.ObjectId;
}
