/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run $> yarn doc
 */
const { Types } = require("mongoose");

export interface User {
  /**
   * Le nom de l'utilisateur
   */
  username?: string | null;
  /**
   * Le mot de passe hashé
   */
  password?: string | null;
  /**
   * true si l'utilisateur est administrateur
   */
  isAdmin?: boolean;
  /**
   * Tag libre
   */
  tag?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Academie coma separated
   */
  academie?: string | null;
  /**
   * Account status
   */
  account_status?: string;
  /**
   * Roles de l'utilisateur
   */
  roles?: string[];
  /**
   * Access control level array
   */
  acl?: string[] | null;
  /**
   * Date de dernière connexion
   */
  last_connection?: Date;
  /**
   * Historique des dates de connexion
   */
  connection_history?: Date[] | null;
  _id?: Types.ObjectId;
  updated_at?: Date;
  created_at?: Date;
}
