const mapping = (old) => {
  return {
    etablissement_gestionnaire_id: old.etablissement_responsable_id,
    etablissement_gestionnaire_siret: old.etablissement_responsable_siret,
    etablissement_gestionnaire_enseigne: old.etablissement_responsable_enseigne,
    etablissement_gestionnaire_uai: old.etablissement_responsable_uai,
    etablissement_gestionnaire_type: old.etablissement_responsable_type,
    etablissement_gestionnaire_conventionne: old.etablissement_responsable_conventionne,
    etablissement_gestionnaire_declare_prefecture: old.etablissement_responsable_declare_prefecture,
    etablissement_gestionnaire_datadock: old.etablissement_responsable_datadock,
    etablissement_gestionnaire_published: old.etablissement_responsable_published,
    etablissement_gestionnaire_catalogue_published: old.etablissement_responsable_catalogue_published,
    etablissement_gestionnaire_adresse: old.etablissement_responsable_adresse,
    etablissement_gestionnaire_code_postal: old.etablissement_responsable_code_postal,
    etablissement_gestionnaire_localite: old.etablissement_responsable_localite,
    etablissement_gestionnaire_complement_adresse: old.etablissement_responsable_complement_adresse,
    etablissement_gestionnaire_cedex: old.etablissement_responsable_cedex,
    etablissement_gestionnaire_entreprise_raison_sociale: old.etablissement_responsable_entreprise_raison_sociale,
    rncp_etablissement_gestionnaire_habilite: old.rncp_etablissement_responsable_habilite,
    geo_coordonnees_etablissement_gestionnaire: old.geo_coordonnees_etablissement_responsable,
    // 'etablissement_gestionnaire_nom_academie': // TO CREATE,
    // 'etablissement_gestionnaire_num_academie': // TO CREATE,
    // 'etablissement_gestionnaire_siren': // TO CREATE,

    etablissement_formateur_id: old.etablissement_formateur_id,
    etablissement_formateur_siret: old.etablissement_formateur_siret,
    etablissement_formateur_enseigne: old.etablissement_formateur_enseigne,
    etablissement_formateur_uai: old.etablissement_formateur_uai,
    etablissement_formateur_type: old.etablissement_formateur_type,
    etablissement_formateur_conventionne: old.etablissement_formateur_conventionne,
    etablissement_formateur_declare_prefecture: old.etablissement_formateur_declare_prefecture,
    etablissement_formateur_datadock: old.etablissement_formateur_datadock,
    etablissement_formateur_published: old.etablissement_formateur_published,
    etablissement_formateur_catalogue_published: old.etablissement_formateur_catalogue_published,
    etablissement_formateur_adresse: old.etablissement_formateur_adresse,
    etablissement_formateur_code_postal: old.etablissement_formateur_code_postal,
    etablissement_formateur_localite: old.etablissement_formateur_localite,
    etablissement_formateur_complement_adresse: old.etablissement_formateur_complement_adresse,
    etablissement_formateur_cedex: old.etablissement_formateur_cedex,
    etablissement_formateur_entreprise_raison_sociale: old.etablissement_formateur_entreprise_raison_sociale,
    rncp_etablissement_formateur_habilite: old.rncp_etablissement_formateur_habilite,
    geo_coordonnees_etablissement_formateur: old.geo_coordonnees_etablissement_formateur,
    // 'etablissement_formateur_nom_academie': // TO CREATE,
    // 'etablissement_formateur_num_academie': // TO CREATE,
    // 'etablissement_formateur_siren': // TO CREATE,

    cfd: old.educ_nat_code,
    cfd_specialite_lettre: old.educ_nat_specialite_lettre,
    cfd_specialite_libelle: old.educ_nat_specialite_libelle,
    cfd_specialite_libelle_court: old.educ_nat_specialite_libelle_court,
    mef_10_code: old.mef_10_code,
    nom_academie: old.nom_academie,
    num_academie: old.num_academie,
    code_postal: old.code_postal,
    code_commune_insee: old.code_commune_insee,
    num_departement: old.num_departement,
    uai_formation: old.uai_formation,
    nom: old.nom,
    intitule_long: old.intitule_long,
    intitule_court: old.intitule_court,
    diplome: old.diplome,
    niveau: old.niveau,
    onisep_url: old.onisep_url,
    rncp_code: old.rncp_code,
    rncp_intitule: old.rncp_intitule,
    rncp_eligible_apprentissage: old.rncp_eligible_apprentissage,
    rome_codes: old.rome_codes,
    periode: old.periode,
    capacite: old.capacite,
    duree: old.duree,
    annee: old.annee,
    email: old.email,
    parcoursup_reference: old.parcoursup_reference === "OUI",
    parcoursup_a_charger: old.parcoursup_a_charger,
    affelnet_reference: old.affelnet_reference === "OUI",
    affelnet_a_charger: old.affelnet_a_charger,
    source: old.source,
    commentaires: old.commentaires,
    opcos: old.opcos,
    info_opcos: old.info_opcos,
    info_opcos_intitule: old.info_opcos_intitule,
    published: old.published,
    draft: old.draft,
    // 'updates_history': // TO CREATE,
    last_update_who: old.last_modification,
    to_verified: old.to_verified,
    idea_geo_coordonnees_etablissement: old.idea_geo_coordonnees_etablissement,
    _id: old._id,
    created_at: old.created_at,
    last_update_at: old.last_update_at,
  };
};

module.exports = { mapping };
