import { escapeDiacritics } from "../../utils/downloadUtils";

const FILTERS = (context) => [
  `QUERYBUILDER-${context}`,
  `SEARCH-${context}`,
  // `num_departement-${context}`,
  `nom_academie-${context}`,
  // `tags-${context}`,
  "statut_reconciliation",
];

const columnsDefinition = [
  {
    Header: "Identifiant ParcourSup",
    accessor: "id_parcoursup",
    width: 200,
    editable: false,
  },
  {
    Header: "Nom de l'academie",
    accessor: "nom_academie",
    width: 200,
    editable: false,
    formatter: (value) => escapeDiacritics(value),
  },
  {
    Header: "Code du diplome ou du titre suivant la nomenclature de l'Education nationale (CodeEN)",
    accessor: "codes_cfd_mna",
    width: 400,
    editable: false,
  },
  {
    Header: "Libelle de la formation",
    accessor: "libelle_formation",
    width: 400,
    editable: false,
  },
  {
    Header: "Libelle de la formation",
    accessor: "libelle_specialite",
    width: 400,
    editable: false,
  },
  // {
  //   Header: "Siret",
  //   accessor: "siret",
  //   width: 200,
  //   editable: false,
  // },
  // {
  //   Header: "Nom / Enseigne",
  //   accessor: "enseigne",
  //   width: 200,
  //   editable: false,
  //   formatter: (value) => escapeDiacritics(value),
  // },
  // {
  //   Header: "Raison sociale de l'entreprise",
  //   accessor: "entreprise_raison_sociale",
  //   width: 200,
  //   editable: false,
  //   formatter: (value) => escapeDiacritics(value),
  // },
  // {
  //   Header: "Code NAF",
  //   accessor: "naf_code",
  //   width: 200,
  //   debug: true,
  //   editable: false,
  // },
  // {
  //   Header: "Libelle du code NAT",
  //   accessor: "naf_libelle",
  //   width: 200,
  //   debug: true,
  //   editable: false,
  // },
  // {
  //   Header: "Uai",
  //   accessor: "uai",
  //   width: 200,
  //   editorInput: "text",
  //   editable: true,
  // },
  // {
  //   Header: "CFA ou OFA ? ",
  //   accessor: "computed_type",
  //   width: 200,
  //   editable: false,
  // },
  // {
  //   Header: "CFA conventionne ? ",
  //   accessor: "computed_conventionne",
  //   width: 200,
  //   editable: false,
  // },
  // {
  //   Header: "CFA declare en prefecture ? ",
  //   accessor: "computed_declare_prefecture",
  //   width: 200,
  //   editable: false,
  // },
  // {
  //   Header: "Organisme certifie 2015 ? ",
  //   accessor: "computed_info_datadock",
  //   width: 200,
  //   editable: false,
  //   formatter: (value) => escapeDiacritics(value),
  // },
  // {
  //   Header: "Est le siege de l'entreprise",
  //   accessor: "siege_social",
  //   width: 200,
  //   editable: false,
  // },
  // {
  //   Header: "Siret Siege social",
  //   accessor: "etablissement_siege_siret",
  //   width: 200,
  //   editable: false,
  // },
  // {
  //   Header: "Adresse",
  //   accessor: "adresse",
  //   width: 200,
  //   editable: false,
  //   formatter: (value) => escapeDiacritics(value),
  // },
  // {
  //   Header: "Numero de voie",
  //   accessor: "numero_voie",
  //   width: 60,
  //   editable: false,
  // },
  // {
  //   Header: "Type de voie",
  //   accessor: "type_voie",
  //   width: 60,
  //   editable: false,
  // },
  // {
  //   Header: "Nom de la voie",
  //   accessor: "nom_voie",
  //   width: 200,
  //   editable: false,
  // },
  // {
  //   Header: "Complement d'adresse",
  //   accessor: "complement_adresse",
  //   width: 200,
  //   editable: false,
  //   formatter: (value) => escapeDiacritics(value),
  // },
  {
    Header: "Code postal",
    accessor: "code_postal",
    width: 120,
    editable: false,
  },
  // {
  //   Header: "Numero de departement",
  //   accessor: "num_departement",
  //   width: 120,
  //   editable: false,
  // },
  {
    Header: "Localite",
    accessor: "libelle_commune",
    width: 200,
    editable: false,
    formatter: (value) => escapeDiacritics(value),
  },
  {
    Header: "match",
    accessor: "matching_mna_formation",
    width: 200,
    editable: false,
    formatter: (value) => escapeDiacritics(value),
  },
  {
    Header: "statut_reconciliation",
    accessor: "statut_reconciliation",
    width: 200,
    editable: false,
    formatter: (value) => escapeDiacritics(value),
  },
  // {
  //   Header: "Code commune INSEE",
  //   accessor: "code_insee_localite",
  //   width: 200,
  //   editable: false,
  // },
  // {
  //   Header: "Cedex",
  //   accessor: "cedex",
  //   width: 200,
  //   editable: false,
  // },
  // {
  //   Header: "Region",
  //   accessor: "region_implantation_nom",
  //   width: 200,
  //   editable: false,
  //   formatter: (value) => escapeDiacritics(value),
  // },
  // {
  //   Header: "Numero academie",
  //   accessor: "num_academie",
  //   width: 200,
  //   editable: false,
  // },
  // {
  //   Header: "Nom de l'academie",
  //   accessor: "nom_academie",
  //   width: 200,
  //   editable: false,
  //   formatter: (value) => escapeDiacritics(value),
  // },
  // {
  //   Header: "A charger dans Affelnet",
  //   accessor: "affelnet_a_charger",
  //   width: 200,
  //   debug: true,
  //   editable: false,
  // },
  // {
  //   Header: "A charger dans ParcourSup",
  //   accessor: "parcoursup_a_charger",
  //   width: 200,
  //   editable: false,
  // },
  // {
  //   Header: "Email",
  //   accessor: "ds_questions_email",
  //   width: 200,
  //   debug: true,
  //   exportOnly: true,
  //   editable: false,
  // },
  // {
  //   Header: "Tags",
  //   accessor: "tags",
  //   width: 200,
  //   editable: false,
  //   formatter: (tags) => tags?.sort((a, b) => a - b),
  // },
];

const queryBuilderField = [
  { text: "Identifiant parcoursup", value: "id_parcoursup.keyword" },
  // { text: "Siret", value: "siret.keyword" },
  // { text: "Type d'établissement", value: "computed_type.keyword" },
  // { text: "Conventionné", value: "computed_conventionne.keyword" },
  // { text: "Déclaré en prefecture", value: "computed_declare_prefecture.keyword" },
  // { text: "Référencé datadock", value: "computed_info_datadock.keyword" },
  // { text: "Uai", value: "uai.keyword" },
];

const facetDefinition = (context) => [
  {
    componentId: `nom_academie-${context}`,
    dataField: "nom_academie.keyword",
    title: "Académie",
    filterLabel: "Académie",
    selectAllLabel: "Toutes les académies",
    sortBy: "asc",
  },
  // {
  //   componentId: `num_departement-${context}`,
  //   dataField: "num_departement.keyword",
  //   title: "Département",
  //   filterLabel: "Département",
  //   selectAllLabel: "Tous",
  //   sortBy: "asc",
  // },
  // {
  //   componentId: `tags-${context}`,
  //   dataField: "tags.keyword",
  //   title: "Année(s)",
  //   filterLabel: "Année(s)",
  //   selectAllLabel: "Toutes",
  //   sortBy: "asc",
  // },
];

const dataSearch = {
  dataField: ["uai_gestionnaire", "id_parcoursup", "libelle_commune"],
  placeholder: "Saisissez un UAI, indentifiant parcoursup ou une commune",
  fieldWeights: [3, 2, 1],
};

export default {
  FILTERS,
  columnsDefinition,
  facetDefinition,
  queryBuilderField,
  dataSearch,
};
