/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run > yarn doc
 */
const { Types } = require("mongoose");

export interface BcnFormationDiplomes {
  /**
   * DESCRIPTION
   */
  FORMATION_DIPLOME?: string | null;
  /**
   * DESCRIPTION
   */
  NIVEAU_FORMATION_DIPLOME?: string | null;
  /**
   * DESCRIPTION
   */
  GROUPE_SPECIALITE?: string | null;
  /**
   * DESCRIPTION
   */
  LETTRE_SPECIALITE?: string | null;
  /**
   * DESCRIPTION
   */
  ANCIEN_RECME?: string | null;
  /**
   * DESCRIPTION
   */
  LIBELLE_COURT?: string | null;
  /**
   * DESCRIPTION
   */
  LIBELLE_STAT_33?: string | null;
  /**
   * DESCRIPTION
   */
  LIBELLE_LONG_200?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_OUVERTURE?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_FERMETURE?: string | null;
  /**
   * DESCRIPTION
   */
  ANCIEN_DIPLOME_1?: string | null;
  /**
   * DESCRIPTION
   */
  ANCIEN_DIPLOME_2?: string | null;
  /**
   * DESCRIPTION
   */
  ANCIEN_DIPLOME_3?: string | null;
  /**
   * DESCRIPTION
   */
  ANCIEN_DIPLOME_4?: string | null;
  /**
   * DESCRIPTION
   */
  ANCIEN_DIPLOME_5?: string | null;
  /**
   * DESCRIPTION
   */
  ANCIEN_DIPLOME_6?: string | null;
  /**
   * DESCRIPTION
   */
  ANCIEN_DIPLOME_7?: string | null;
  /**
   * DESCRIPTION
   */
  NOUVEAU_DIPLOME_1?: string | null;
  /**
   * DESCRIPTION
   */
  NOUVEAU_DIPLOME_2?: string | null;
  /**
   * DESCRIPTION
   */
  NOUVEAU_DIPLOME_3?: string | null;
  /**
   * DESCRIPTION
   */
  NOUVEAU_DIPLOME_4?: string | null;
  /**
   * DESCRIPTION
   */
  NOUVEAU_DIPLOME_5?: string | null;
  /**
   * DESCRIPTION
   */
  NOUVEAU_DIPLOME_6?: string | null;
  /**
   * DESCRIPTION
   */
  NOUVEAU_DIPLOME_7?: string | null;
  /**
   * DESCRIPTION
   */
  UNITE_CAPITALISABLE?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_PREMIERE_SESSION?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_DERNIERE_SESSION?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_ARRETE_CREATION?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_ARRETE_ABROGATION?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_ARRETE_MODIFICATION_1?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_ARRETE_MODIFICATION_2?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_ARRETE_MODIFICATION_3?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_ARRETE_MODIFICATION_4?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_ARRETE_MODIFICATION_5?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_ARRETE_MODIFICATION_6?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_ARRETE_MODIFICATION_7?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_ARRETE_MODIFICATION_8?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_ARRETE_MODIFICATION_9?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_ARRETE_MODIFICATION_10?: string | null;
  /**
   * DESCRIPTION
   */
  COMMENTAIRE?: string | null;
  /**
   * DESCRIPTION
   */
  NATURE_FORMATION_DIPLOME?: string | null;
  /**
   * DESCRIPTION
   */
  GESTIONNAIRE_FORMATION_DIPLOME?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_INTERVENTION?: string | null;
  /**
   * DESCRIPTION
   */
  NUMERO_COMPTE?: string | null;
  /**
   * DESCRIPTION
   */
  GESTION_DIFFUSION?: string | null;
  /**
   * DESCRIPTION
   */
  NB_MEF_OUVERT?: string | null;
  /**
   * DESCRIPTION
   */
  NB_MEF_FERME?: string | null;
  /**
   * DESCRIPTION
   */
  ID_DOCUMENT?: string | null;
  /**
   * DESCRIPTION
   */
  CITE_DOMAINE_FORMATION?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_SESSION_RATTRAPAGE?: string | null;
  /**
   * DESCRIPTION
   */
  OBSERVATION?: string | null;
  /**
   * DESCRIPTION
   */
  ID?: string | null;
  /**
   * DESCRIPTION
   */
  CREATED_AT?: string | null;
  /**
   * DESCRIPTION
   */
  UPDATED_AT?: string | null;
  /**
   * DESCRIPTION
   */
  N_COMMENTAIRE?: string | null;
  /**
   * DESCRIPTION
   */
  CITE_DOMAINE_DETAILLE?: string | null;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
  /**
   * Date de dernières mise à jour
   */
  last_update_at?: Date;
  _id?: Types.ObjectId;
}
