/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run > yarn doc
 */
const { Types } = require("mongoose");

export interface BcnNMef {
  /**
   * DESCRIPTION
   */
  MEF?: string | null;
  /**
   * DESCRIPTION
   */
  DISPOSITIF_FORMATION?: string | null;
  /**
   * DESCRIPTION
   */
  FORMATION_DIPLOME?: string | null;
  /**
   * DESCRIPTION
   */
  DUREE_DISPOSITIF?: string | null;
  /**
   * DESCRIPTION
   */
  ANNEE_DISPOSITIF?: string | null;
  /**
   * DESCRIPTION
   */
  LIBELLE_COURT?: string | null;
  /**
   * DESCRIPTION
   */
  LIBELLE_LONG?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_OUVERTURE?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_FERMETURE?: string | null;
  /**
   * DESCRIPTION
   */
  STATUT_MEF?: string | null;
  /**
   * DESCRIPTION
   */
  NB_OPTION_OBLIGATOIRE?: string | null;
  /**
   * DESCRIPTION
   */
  NB_OPTION_FACULTATIF?: string | null;
  /**
   * DESCRIPTION
   */
  RENFORCEMENT_LANGUE?: string | null;
  /**
   * DESCRIPTION
   */
  DUREE_PROJET?: string | null;
  /**
   * DESCRIPTION
   */
  DUREE_STAGE?: string | null;
  /**
   * DESCRIPTION
   */
  HORAIRE?: string | null;
  /**
   * DESCRIPTION
   */
  MEF_INSCRIPTION_SCOLARITE?: string | null;
  /**
   * DESCRIPTION
   */
  MEF_STAT_11?: string | null;
  /**
   * DESCRIPTION
   */
  MEF_STAT_9?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_INTERVENTION?: string | null;
  /**
   * DESCRIPTION
   */
  NUMERO_COMPTE?: string | null;
  /**
   * DESCRIPTION
   */
  GESTION_DIFFUSION?: string | null;
  /**
   * DESCRIPTION
   */
  LIBELLE_EDITION?: string | null;
  /**
   * DESCRIPTION
   */
  ID?: string | null;
  /**
   * DESCRIPTION
   */
  CREATED_AT?: string | null;
  /**
   * DESCRIPTION
   */
  UPDATED_AT?: string | null;
  /**
   * DESCRIPTION
   */
  N_COMMENTAIRE?: string | null;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
  /**
   * Date de dernières mise à jour
   */
  last_update_at?: Date;
  _id?: Types.ObjectId;
}
