/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run > yarn doc
 */
const { Types } = require("mongoose");

export interface BcnNNiveauFormationDiplome {
  /**
   * DESCRIPTION
   */
  NIVEAU_FORMATION_DIPLOME?: string | null;
  /**
   * DESCRIPTION
   */
  NIVEAU_INTERMINISTERIEL?: string | null;
  /**
   * DESCRIPTION
   */
  LIBELLE_COURT?: string | null;
  /**
   * DESCRIPTION
   */
  LIBELLE_100?: string | null;
  /**
   * DESCRIPTION
   */
  ANCIEN_NIVEAU?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_OUVERTURE?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_FERMETURE?: string | null;
  /**
   * DESCRIPTION
   */
  DATE_INTERVENTION?: string | null;
  /**
   * DESCRIPTION
   */
  NUMERO_COMPTE?: string | null;
  /**
   * DESCRIPTION
   */
  GESTION_DIFFUSION?: string | null;
  /**
   * DESCRIPTION
   */
  ID?: string | null;
  /**
   * DESCRIPTION
   */
  CREATED_AT?: string | null;
  /**
   * DESCRIPTION
   */
  UPDATED_AT?: string | null;
  /**
   * DESCRIPTION
   */
  N_COMMENTAIRE?: string | null;
  /**
   * Date d'ajout en base de données
   */
  created_at?: Date;
  /**
   * Date de dernières mise à jour
   */
  last_update_at?: Date;
  _id?: Types.ObjectId;
}
