/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run > yarn doc
 */
const { Types } = require("mongoose");

export interface CandidatureFormation {
  /**
   * Affelnet ID de la formation
   */
  affelnet_id?: string | null;
  /**
   * Académie de la formation
   */
  academie_formation?: string | null;
  /**
   * Code offre de la formation
   */
  code_offre_formation?: string | null;
  /**
   * Localité de l'établissement d'accueil
   */
  localite_formation?: string;
  /**
   * UAI de l'établissement d'accueil
   */
  uai_formation?: string;
  /**
   * Académie de l'établissement responsable
   */
  academie_responsable?: string | null;
  /**
   * SIRET de l'établissement responsable
   */
  siret_responsable?: string | null;
  /**
   * UAI de l'établissement responsable
   */
  uai_responsable?: string | null;
  /**
   * SIRET de l'établissement responsable
   */
  url_responsable?: string | null;
  /**
   * UAI de l'établissement responsable
   */
  raison_sociale_responsable?: string | null;
  /**
   * UAI de l'établissement responsable
   */
  localite_responsable?: string | null;
  /**
   * Email de l'établissement responsable
   */
  email_responsable?: string | null;
  /**
   * Académie de l'établissement formateur
   */
  academie_formateur?: string | null;
  /**
   * SIRET de l'établissement formateur
   */
  siret_formateur?: string | null;
  /**
   * UAI de l'établissement formateur
   */
  uai_formateur?: string | null;
  /**
   * Raison sociale de l'établissement formateur
   */
  raison_sociale_formateur?: string | null;
  /**
   * Délégation autorisée
   */
  active_delegue?: boolean;
  /**
   * Email du délégué
   */
  email_delegue?: string | null;
  /**
   * Statut de création du compte
   */
  statut_creation?: string | null;
  /**
   * Statut de diffusion des candidatures
   */
  statut_diffusion?: string | null;
  /**
   * Statut générique
   */
  statut_diffusion_generique?: string | null;
  /**
   * Nombre de vœux
   */
  nombre_voeux?: number;
  /**
   * Date du dernier import de vœux
   */
  last_import_voeux?: Date;
  /**
   * Téléchargement
   */
  telechargement?: boolean;
  /**
   * Date du dernier téléchargement
   */
  telechargement_date?: Date;
  /**
   * Vœux téléchargés par le destinataire principal
   */
  nombre_voeux_telecharges?: number;
  /**
   * Vœux à télécharger pour mise à jour
   */
  nombre_voeux_a_retelecharges?: number;
  /**
   * Vœux jamais téléchargés par le destinataire principal
   */
  nombre_voeux_jamais_telecharges?: number;
  /**
   * Intervention par un administrateur
   */
  admin_intervention?: string | null;
  _id?: Types.ObjectId;
  created_at?: Date;
  updated_at?: Date;
}
