/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run > yarn doc
 */
const { Types } = require("mongoose");

export interface Config {
  rco_import: boolean & number;
  affelnet_diffusion: boolean;
  parcoursup_export: boolean;
  parcoursup_limit: number;
  _id?: Types.ObjectId;
  created_at?: Date;
  updated_at?: Date;
}
