/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run > yarn doc
 */
const { Types } = require("mongoose");

export interface ConsoleStat {
  /**
   * Plateforme de destination
   */
  plateforme: "affelnet" | "parcoursup";
  /**
   * Date de la statistique
   */
  date: Date;
  academie?: string | null;
  region?: string | null;
  formations_publiees?: number;
  formations_publiees_sans_session?: number;
  formations_publiees_sans_session_avec_remplacement?: number;
  formations_publiees_sans_session_sans_remplacement?: number;
  formations_publiees_perte_qualiopi?: number;
  formations_publiees_perte_rncp?: number;
  formations_publiees_siret_inactif?: number;
  formations_integrables?: number;
  formations_perimetre?: number;
  organismes_avec_formations_publiees?: number;
  organismes_avec_formations_publiees_sans_session?: number;
  organismes_avec_formations_integrables?: number;
  organismes_avec_formations_perimetre?: number;
  details?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
