/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run > yarn doc
 */
const { Types } = require("mongoose");

/**
 * Détails RNCP (bloc de compétences etc..)
 */
export type RncpDetails = {
  /**
   * Date de validité de la fiche
   */
  date_fin_validite_enregistrement?: Date;
  /**
   * fiche active ou non
   */
  active_inactive?: string | null;
  /**
   * état fiche ex: Publiée
   */
  etat_fiche_rncp?: string | null;
  /**
   * Niveau européen ex: niveauu5
   */
  niveau_europe?: string | null;
  /**
   * Code type de certification (ex: DE)
   */
  code_type_certif?: string | null;
  /**
   * Type de certification (ex: diplôme d'état)
   */
  type_certif?: string | null;
  /**
   * Code rncp de l'ancienne fiche
   */
  ancienne_fiche?: string[] | null;
  /**
   * Code rncp de la nouvelle fiche
   */
  nouvelle_fiche?: string[] | null;
  /**
   * Certificateurs
   */
  certificateurs?: ItemOfCertificateurs[];
  /**
   * Code NSF
   */
  nsf_code?: string | null;
  /**
   * Romes
   */
  romes?: ItemOfRomes[];
  /**
   * Partenaires
   */
  partenaires?: ItemOfPartenaires[];
  /**
   * Code rncp périmé (date fin enregistrement avant le 31 aout de l'année courante)
   */
  rncp_outdated?: boolean;
  /**
   * Type d'enregistrement (issue de FranceCompétences)
   */
  type_enregistrement?: string | null;
} | null;

export interface DualControlFormation {
  /**
   * Clé unique de la formation (pour envoi aux ministères éducatifs)
   */
  cle_ministere_educatif?: string | null;
  /**
   * Code formation diplôme (education nationale)
   */
  cfd?: string | null;
  /**
   * Lettre spécialité du code cfd
   */
  cfd_specialite?: {
    [k: string]: unknown;
  } | null;
  /**
   * BCN : cfd périmé (fermeture avant le 31 août de l'année courante)
   */
  cfd_outdated?: boolean;
  /**
   * Date de fermeture du cfd
   */
  cfd_date_fermeture?: Date;
  /**
   * Code formacode
   */
  code_formacode?: unknown[];
  /**
   * Libelle formacode
   */
  libelle_formacode?: unknown[];
  /**
   * Nom de l'académie
   */
  nom_academie?: string | null;
  /**
   * Numéro de l'académie
   */
  num_academie?: string;
  /**
   * Code postal
   */
  code_postal?: string | null;
  /**
   * Code commune INSEE
   */
  code_commune_insee?: string | null;
  /**
   * Numéro de département
   */
  num_departement?: string | null;
  /**
   * Nom du département
   */
  nom_departement?: string | null;
  /**
   * Numéro de département
   */
  region?: string | null;
  /**
   * Localité
   */
  localite?: string | null;
  /**
   * Nom de la formation déclaratif
   */
  nom?: string | null;
  /**
   * Intitulé comme transmis par RCO
   */
  intitule_rco?: string | null;
  /**
   * Intitulé long de la formation normalisé BCN
   */
  intitule_long?: string | null;
  /**
   * Intitulé court de la formation normalisé BCN
   */
  intitule_court?: string | null;
  /**
   * Diplôme ou titre visé
   */
  diplome?: string | null;
  /**
   * Niveau de la formation
   */
  niveau?: string | null;
  /**
   * Périodes de début de la formation
   */
  periode?: Date[];
  /**
   * Capacité d'accueil
   */
  capacite?: string | null;
  /**
   * Durée de la formation en années
   */
  duree?: string | null;
  /**
   * Année de la formation (cursus)
   */
  annee?: string | null;
  /**
   * Url de redirection vers le site de l'ONISEP
   */
  onisep_url?: string | null;
  /**
   * Intitulé éditorial l'ONISEP
   */
  onisep_intitule?: string | null;
  /**
   * Disciplines ONISEP (séparateur ;)
   */
  onisep_discipline?: string | null;
  /**
   * Domaine et sous domaine ONISEP (séparateur ;)
   */
  onisep_domaine_sousdomaine?: string | null;
  /**
   * Code RNCP
   */
  rncp_code?: string | null;
  /**
   * Intitulé du code RNCP
   */
  rncp_intitule?: string | null;
  /**
   * Le titre RNCP est éligible en apprentissage
   */
  rncp_eligible_apprentissage?: boolean;
  rncp_details?: RncpDetails;
  /**
   * Codes ROME
   */
  rome_codes?: string[];
  /**
   * Est publiée, la formation est éligible pour le catalogue
   */
  published?: boolean;
  /**
   * Siret du lieu de formation
   */
  etablissement_lieu_formation_siret?: string | null;
  /**
   * UAI du lieu de formation (transmis par RCO)
   */
  etablissement_lieu_formation_uai?: string | null;
  /**
   * Siret du lieu de formation actif / inactif
   */
  etablissement_lieu_siret_actif?: string | null;
  /**
   * Latitude et longitude du lieu de formation
   */
  lieu_formation_geo_coordonnees?: string;
  /**
   * Latitude et longitude du lieu de formation déduit de l'adresse du flux RCO
   */
  lieu_formation_geo_coordonnees_computed?: string;
  /**
   * Adresse du lieu de formation
   */
  lieu_formation_adresse?: string | null;
  /**
   * Adresse du lieu de formation déduit de la géolocalisation du flux RCO
   */
  lieu_formation_adresse_computed?: string | null;
  /**
   * **[DEPRECATED]** Id de formation RCO (id_formation + id_action + id_certifinfo)
   */
  id_rco_formation?: string | null;
  /**
   * Identifiant de la formation
   */
  id_formation?: string | null;
  /**
   * Identifiant des actions concaténés
   */
  id_action?: string | null;
  /**
   * Identifiant des actions concaténés
   */
  ids_action?: string[];
  /**
   * Identifiant certifInfo (unicité de la certification)
   */
  id_certifinfo?: string | null;
  /**
   * Tableau de tags (2020, 2021, etc.)
   */
  tags?: string[];
  /**
   * BCN : libelle court fusion table n_formation_diplome ou v_formation_diplome
   */
  libelle_court?: string | null;
  /**
   * BCN : niveau formation diplôme
   */
  niveau_formation_diplome?: string | null;
  /**
   * BCN : Codes MEF 10 caractères
   */
  bcn_mefs_10?: ItemOfBcnMefs_10[];
  /**
   * Niveau d'entrée de l'apprenti minimum obligatoire pour cette formation
   */
  niveau_entree_obligatoire?: number | null;
  /**
   * Renseigné si la formation peut être suivie entièrement à distance
   */
  entierement_a_distance?: boolean;
  /**
   * Formation éligible au catalogue générale
   */
  catalogue_published?: boolean;
  /**
   * Formation éligible au catalogue générale
   */
  date_debut?: Date[];
  /**
   * Formation éligible au catalogue générale
   */
  date_fin?: Date[];
  /**
   * Session en entrée / sortie permanente
   */
  modalites_entrees_sorties?: boolean[];
  capacite_minimal?: string[];
  capacite_simultanee?: string[];
  capacite_cumulee?: string[];
  /**
   * Identifiant RCO
   */
  id_RCO?: string | null;
  /**
   * Type d'enregistrement (issue de CertifInfo)
   */
  CI_inscrit_rncp?: string | null;
  /**
   * Badge siret actif/inactif
   */
  siret_actif?: string | null;
  /**
   * Est remplacée par la clé ME
   */
  cle_me_remplace_par?: string[] | null;
  /**
   * Remplace la clé ME
   */
  cle_me_remplace?: string[] | null;
  /**
   * Numéro siret gestionnaire
   */
  etablissement_gestionnaire_siret?: string | null;
  /**
   * Enseigne établissement gestionnaire
   */
  etablissement_gestionnaire_enseigne?: string | null;
  /**
   * UAI de l'etablissement gestionnaire
   */
  etablissement_gestionnaire_uai?: string | null;
  /**
   * Etablissement gestionnaire est habilité RNCP ou pas
   */
  etablissement_gestionnaire_habilite_rncp?: boolean;
  /**
   * Etablissement gestionnaire est certifié Qualité
   */
  etablissement_gestionnaire_certifie_qualite?: boolean;
  /**
   * Numéro et rue établissement gestionnaire
   */
  etablissement_gestionnaire_adresse?: string | null;
  /**
   * Code postal établissement gestionnaire
   */
  etablissement_gestionnaire_code_postal?: string | null;
  /**
   * Code commune insee établissement gestionnaire
   */
  etablissement_gestionnaire_code_commune_insee?: string | null;
  /**
   * Localité établissement gestionnaire
   */
  etablissement_gestionnaire_localite?: string | null;
  /**
   * Complément d'adresse de l'établissement gestionnaire
   */
  etablissement_gestionnaire_complement_adresse?: string | null;
  /**
   * Cedex
   */
  etablissement_gestionnaire_cedex?: string | null;
  /**
   * Raison sociale établissement gestionnaire
   */
  etablissement_gestionnaire_entreprise_raison_sociale?: string | null;
  /**
   * Raison sociale et enseigne de l'établissement formateur
   */
  etablissement_gestionnaire_raison_sociale_enseigne?: string | null;
  /**
   * Latitude et longitude de l'établissement gestionnaire
   */
  geo_coordonnees_etablissement_gestionnaire?: string;
  /**
   * région gestionnaire
   */
  etablissement_gestionnaire_region?: string | null;
  /**
   * Numéro de departement gestionnaire
   */
  etablissement_gestionnaire_num_departement?: string | null;
  /**
   * Nom du departement gestionnaire
   */
  etablissement_gestionnaire_nom_departement?: string | null;
  /**
   * Nom de l'académie gestionnaire
   */
  etablissement_gestionnaire_nom_academie?: string | null;
  /**
   * Numéro de l'académie gestionnaire
   */
  etablissement_gestionnaire_num_academie?: string;
  /**
   * Numéro siren gestionnaire
   */
  etablissement_gestionnaire_siren?: string | null;
  /**
   * Numéro Déclaration gestionnaire
   */
  etablissement_gestionnaire_nda?: string | null;
  /**
   * Date de création de l'établissement
   */
  etablissement_gestionnaire_date_creation?: Date;
  /**
   * Adresse email de contact de l'établissement gestionnaire
   */
  etablissement_gestionnaire_courriel?: string | null;
  /**
   * SIRET actif ou inactif pour l'établissement gestionnaire
   */
  etablissement_gestionnaire_actif?: string | null;
  /**
   * Numéro siret formateur
   */
  etablissement_formateur_siret?: string | null;
  /**
   * Enseigne établissement formateur
   */
  etablissement_formateur_enseigne?: string | null;
  /**
   * UAI de l'etablissement formateur
   */
  etablissement_formateur_uai?: string | null;
  /**
   * Etablissement formateur est habilité RNCP ou pas
   */
  etablissement_formateur_habilite_rncp?: boolean;
  /**
   * Etablissement formateur est certifié Qualité
   */
  etablissement_formateur_certifie_qualite?: boolean;
  /**
   * Numéro et rue établissement formateur
   */
  etablissement_formateur_adresse?: string | null;
  /**
   * Code postal établissement formateur
   */
  etablissement_formateur_code_postal?: string | null;
  /**
   * Code commune insee établissement formateur
   */
  etablissement_formateur_code_commune_insee?: string | null;
  /**
   * Localité établissement formateur
   */
  etablissement_formateur_localite?: string | null;
  /**
   * Complément d'adresse de l'établissement
   */
  etablissement_formateur_complement_adresse?: string | null;
  /**
   * Cedex
   */
  etablissement_formateur_cedex?: string | null;
  /**
   * Raison sociale établissement formateur
   */
  etablissement_formateur_entreprise_raison_sociale?: string | null;
  /**
   * Raison sociale et enseigne de l'établissement formateur
   */
  etablissement_formateur_raison_sociale_enseigne?: string | null;
  /**
   * Latitude et longitude de l'établissement formateur
   */
  geo_coordonnees_etablissement_formateur?: string;
  /**
   * région formateur
   */
  etablissement_formateur_region?: string | null;
  /**
   * Numéro de departement formateur
   */
  etablissement_formateur_num_departement?: string | null;
  /**
   * Nom du departement formateur
   */
  etablissement_formateur_nom_departement?: string | null;
  /**
   * Nom de l'académie formateur
   */
  etablissement_formateur_nom_academie?: string | null;
  /**
   * Numéro de l'académie formateur
   */
  etablissement_formateur_num_academie?: string;
  /**
   * Numéro siren formateur
   */
  etablissement_formateur_siren?: string | null;
  /**
   * Numéro Déclaration formateur
   */
  etablissement_formateur_nda?: string | null;
  /**
   * Date de création de l'établissement
   */
  etablissement_formateur_date_creation?: Date;
  /**
   * Adresse email de contact de l'établissement formateur
   */
  etablissement_formateur_courriel?: string | null;
  /**
   * SIRET actif ou inactif pour l'établissement formateur
   */
  etablissement_formateur_actif?: string | null;
  /**
   * Etablissement reference est soit formateur soit le gestionnaire
   */
  etablissement_reference?: string | null;
  /**
   * Etablissement reference est publié
   */
  etablissement_reference_published?: boolean;
  /**
   * Etablissement reference est habilité RNCP ou pas
   */
  etablissement_reference_habilite_rncp?: boolean;
  /**
   * Etablissement reference est certifié Qualité
   */
  etablissement_reference_certifie_qualite?: boolean;
  /**
   * Date de création de l'établissement
   */
  etablissement_reference_date_creation?: Date;
  _id?: Types.ObjectId;
}
export interface ItemOfCertificateurs {
  certificateur?: string;
  siret_certificateur?: string;
}
export interface ItemOfRomes {
  rome?: string;
  libelle?: string;
}
export interface ItemOfPartenaires {
  Nom_Partenaire?: string;
  Siret_Partenaire?: string;
  Habilitation_Partenaire?: string;
}
export interface ItemOfBcnMefs_10 {
  mef10?: string;
  modalite?: Modalite;
  date_fermeture?: Date;
  _id?: Types.ObjectId;
}
export interface Modalite {
  duree?: string;
  annee?: string;
}
