/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run > yarn doc
 */
const { Types } = require("mongoose");

export interface Etablissement {
  /**
   * Cet établissement est le siége sociale
   */
  siege_social?: boolean;
  /**
   * Identifiant établissement siége
   */
  etablissement_siege_id?: string | null;
  /**
   * Numéro siret du siége sociale
   */
  etablissement_siege_siret?: string | null;
  /**
   * Numéro siret
   */
  siret?: string | null;
  /**
   * Numéro siren de l'entreprise
   */
  siren?: string | null;
  /**
   * Numéro Déclaration
   */
  nda?: string | null;
  /**
   * Code NAF
   */
  naf_code?: string | null;
  /**
   * Libellé du code NAT (ex: Enseignement secondaire technique ou professionnel)
   */
  naf_libelle?: string | null;
  /**
   * Tranche salariale
   */
  tranche_effectif_salarie?: {
    [k: string]: unknown;
  };
  /**
   * Date de création
   */
  date_creation?: Date;
  /**
   * Date de création
   */
  date_mise_a_jour?: Date;
  /**
   * Diffusable commercialement
   */
  diffusable_commercialement?: boolean;
  /**
   * Enseigne
   */
  enseigne?: string | null;
  /**
   * Raison social et enseigne (pour recherche)
   */
  raison_sociale_enseigne?: string | null;
  /**
   * Nom de l'etablissement Onisep
   */
  onisep_nom?: string | null;
  /**
   * Url Onisep de la fiche etablissement
   */
  onisep_url?: string | null;
  /**
   * Code postal Onisep
   */
  onisep_code_postal?: string | null;
  /**
   * Adresse de l'établissement
   */
  adresse?: string | null;
  /**
   * Numéro de la voie
   */
  numero_voie?: string | null;
  /**
   * Type de voie (ex: rue, avenue)
   */
  type_voie?: string | null;
  /**
   * Nom de la voie
   */
  nom_voie?: string | null;
  /**
   * Complément d'adresse de l'établissement
   */
  complement_adresse?: string | null;
  /**
   * Code postal
   */
  code_postal?: string | null;
  /**
   * Numéro de département
   */
  num_departement?: string | null;
  /**
   * Nom du departement
   */
  nom_departement?: string | null;
  /**
   * Localité
   */
  localite?: string | null;
  /**
   * Code Insee localité
   */
  code_insee_localite?: string | null;
  /**
   * Cedex
   */
  cedex?: string | null;
  /**
   * Latitude et longitude de l'établissement
   */
  geo_coordonnees?: string;
  /**
   * Date de cessation d'activité
   */
  date_fermeture?: Date;
  /**
   * A cessé son activité
   */
  ferme?: boolean;
  /**
   * Code région
   */
  region_implantation_code?: string | null;
  /**
   * Nom de la région
   */
  region_implantation_nom?: string | null;
  /**
   * Code commune
   */
  commune_implantation_code?: string | null;
  /**
   * Nom de la commune
   */
  commune_implantation_nom?: string | null;
  /**
   * Code pays
   */
  pays_implantation_code?: string | null;
  /**
   * Nom du pays
   */
  pays_implantation_nom?: string | null;
  /**
   * Numéro de l'académie
   */
  num_academie?: number;
  /**
   * Nom de l'académie
   */
  nom_academie?: string | null;
  /**
   * UAI de l'établissement
   */
  uai?: string | null;
  /**
   * L'UAI de l'établissement est il valide ?
   */
  uai_valide?: boolean | null;
  /**
   * UAIs potentiels de l'établissement
   */
  uais_potentiels?: string[];
  /**
   * L'établissement est présent ou pas dans le fichier datagouv
   */
  info_datagouv_ofs?: number;
  /**
   * L'établissement est présent ou pas dans le fichier datagouv
   */
  info_datagouv_ofs_info?: string | null;
  /**
   * L'établissement est présent ou pas dans le fichier qualiopi
   */
  info_qualiopi_info?: string | null;
  /**
   * L'établissement est trouvé via l'API Entreprise
   */
  api_entreprise_reference?: boolean;
  /**
   * Numéro siren
   */
  entreprise_siren?: string | null;
  /**
   * Procédure collective
   */
  entreprise_procedure_collective?: boolean;
  /**
   * Enseigne
   */
  entreprise_enseigne?: string | null;
  /**
   * Numéro de TVA intracommunautaire
   */
  entreprise_numero_tva_intracommunautaire?: string | null;
  /**
   * Code éffectf
   */
  entreprise_code_effectif_entreprise?: string | null;
  /**
   * Code forme juridique
   */
  entreprise_forme_juridique_code?: string | null;
  /**
   * Forme juridique (ex: Établissement public local d'enseignement)
   */
  entreprise_forme_juridique?: string | null;
  /**
   * Raison sociale
   */
  entreprise_raison_sociale?: string | null;
  /**
   * Nom commercial
   */
  entreprise_nom_commercial?: string | null;
  /**
   * Capital social
   */
  entreprise_capital_social?: string | null;
  /**
   * Date de création
   */
  entreprise_date_creation?: Date;
  /**
   * Date de radiation
   */
  entreprise_date_radiation?: string | null;
  /**
   * Code NAF
   */
  entreprise_naf_code?: string | null;
  /**
   * Libellé du code NAT (ex: Enseignement secondaire technique ou professionnel)
   */
  entreprise_naf_libelle?: string | null;
  /**
   * Date de cessation d'activité
   */
  entreprise_date_fermeture?: Date;
  /**
   * A cessé son activité
   */
  entreprise_ferme?: boolean;
  /**
   * Numéro siret du siége sociale
   */
  entreprise_siret_siege_social?: string | null;
  /**
   * Nom du contact
   */
  entreprise_nom?: string | null;
  /**
   * Prénom du contact
   */
  entreprise_prenom?: string | null;
  /**
   * Catégorie (PME, TPE, etc..)
   */
  entreprise_categorie?: string | null;
  /**
   * Tranche salarié
   */
  entreprise_tranche_effectif_salarie?: {
    [k: string]: unknown;
  };
  /**
   * Id des formations rattachées
   */
  formations_ids?: string[];
  /**
   * UAIs des formations rattachées à l'établissement
   */
  formations_uais?: string[];
  /**
   * Numéro de dossier Démarche Simplifiée
   */
  ds_id_dossier?: string | null;
  /**
   * Numéro SIREN saisi dans Démarche Simplifiée
   */
  ds_questions_siren?: string | null;
  /**
   * Nom du contact saisi dans Démarche Simplifiée
   */
  ds_questions_nom?: string | null;
  /**
   * UAI saisi dans Démarche Simplifiée
   */
  ds_questions_uai?: string | null;
  /**
   * Réponse à la question "Avez vous l'agrément CFA" dans Démarche Simplifiée
   */
  ds_questions_has_agrement_cfa?: string | null;
  /**
   * Réponse à la question "Avez vous la certification 2015" dans Démarche Simplifiée
   */
  ds_questions_has_certificaton_2015?: string | null;
  /**
   * Réponse à la question "Avez vous demandé la certification" dans Démarche Simplifiée
   */
  ds_questions_has_ask_for_certificaton?: string | null;
  /**
   * Réponse à la question "Date de votre demande de certification" dans Démarche Simplifiée
   */
  ds_questions_ask_for_certificaton_date?: Date;
  /**
   * Réponse à la question "Numéro de votre déclaration" dans Démarche Simplifiée
   */
  ds_questions_declaration_code?: string | null;
  /**
   * Réponse à la question "Proposez-vous des formations en 2020" dans Démarche Simplifiée
   */
  ds_questions_has_2020_training?: string | null;
  /**
   * Possède la certification Qualité
   */
  certifie_qualite?: boolean;
  /**
   * Est publié
   */
  published?: boolean;
  /**
   * Date de dernières mise à jour
   */
  last_update_at?: Date;
  /**
   * Historique des mises à jours
   */
  updates_history?: unknown[];
  /**
   * Erreur lors de la mise à jour de la formation
   */
  update_error?: string | null;
  /**
   * Tableau de tags (2020, 2021, RCO, etc.)
   */
  tags?: string[];
  /**
   * UAI de l'établissement RCO
   */
  rco_uai?: string | null;
  /**
   * Adresse de l'établissement RCO
   */
  rco_adresse?: string | null;
  /**
   * Code postal
   */
  rco_code_postal?: string | null;
  /**
   * Code Insee localité RCO
   */
  rco_code_insee_localite?: string | null;
  /**
   * Latitude et longitude de l'établissement RCO
   */
  rco_geo_coordonnees?: string;
  /**
   * id convention collective
   */
  idcc?: number;
  /**
   * Nom de l'opérateur de compétence
   */
  opco_nom?: string | null;
  /**
   * Siren de l'opérateur de compétence
   */
  opco_siren?: string | null;
  _id?: Types.ObjectId;
  updated_at?: Date;
  created_at?: Date;
}
