/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run > yarn doc
 */
const { Types } = require("mongoose");

/**
 * Champs édités par un utilisateur
 */
export type EditedFields = {
  /**
   * Adresse courriel du directeur de l'établissement responsable éditée
   */
  email_responsable?: string | null;
  _id?: Types.ObjectId;
} | null;

export interface Relation {
  /**
   * SIRET de l'établissement responsable
   */
  siret_responsable?: string | null;
  /**
   * SIRET de l'établissement formateur
   */
  siret_formateur?: string | null;
  /**
   * Adresse courriel du directeur de l'établissement responsable éditée
   */
  email_responsable?: string | null;
  editedFields?: EditedFields;
  /**
   * Historique des mises à jours
   */
  updates_history?: ItemOfUpdatesHistory[];
  /**
   * Date de dernières mise à jour
   */
  last_update_at?: Date;
  /**
   * Qui a réalisé la dernière modification
   */
  last_update_who?: string | null;
  _id?: Types.ObjectId;
  created_at?: Date;
  updated_at?: Date;
}
export interface ItemOfUpdatesHistory {
  /**
   * Valeurs avant mise à jour
   */
  from?: {
    [k: string]: unknown;
  };
  /**
   * Valeurs après mise à jour
   */
  to?: {
    [k: string]: unknown;
  };
  _id?: Types.ObjectId;
}
