/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the Mongoose schema file,
 * To regenerate this file run > yarn doc
 */
const { Types } = require("mongoose");

export interface Role {
  /**
   * Nom du rôle
   */
  name?: string | null;
  /**
   * Access control level array
   */
  acl?: string[] | null;
  _id?: Types.ObjectId;
  updated_at?: Date;
  created_at?: Date;
}
