FROM node:18-alpine

# handle .npmrc : copy local one for dev, create one using NPM_TOKEN arg for production & recette
ARG NPM_TOKEN
COPY .npmrc* /
RUN if [ "$NPM_TOKEN" != "local" ] ; then \
    echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN\n@mission-apprentissage:registry=https://npm.pkg.github.com" > /.npmrc ; \
fi


WORKDIR /app

VOLUME /data
EXPOSE 5000
CMD yarn install && yarn debug
