FROM node:16-alpine

# handle .npmrc : copy local one for dev, create one using NPM_TOKEN arg for production & recette
ARG NPM_TOKEN
COPY .yarnrc.yml* /
RUN if [ "$NPM_TOKEN" != "local" ] ; then \
    echo 'yarnPath: .yarn/releases/yarn-3.3.1.cjs\
nodeLinker: node-modules\
defaultSemverRangePrefix: ""\
\
npmScopes:\
  mission-apprentissage:\
    npmRegistryServer: "https://npm.pkg.github.com"\
    npmPublishRegistry: "https://npm.pkg.github.com"\
    npmAlwaysAuth: true\
    npmAuthToken: $NPM_TOKEN' > /.yarnrc.yml ; \
fi

WORKDIR /app

VOLUME /data
EXPOSE 5000
CMD yarn install && yarn debug
