export const REGIONS = {
  "01": { nom_region: "Guadeloupe", num_region: 1, academies: ["32"] },
  "02": { nom_region: "Martinique", num_region: 2, academies: ["31"] },
  "03": { nom_region: "Guyane", num_region: 3, academies: ["33"] },
  "04": { nom_region: "La Réunion", num_region: 4, academies: ["28"] },
  "06": { nom_region: "Mayotte", num_region: 6, academies: ["43"] },
  11: { nom_region: "Île-de-France", num_region: 11, academies: ["01", "24", "25"] },
  24: { nom_region: "Centre-Val de Loire", num_region: 24, academies: ["18"] },
  27: { nom_region: "Bourgogne-Franche-Comté", num_region: 27, academies: ["03", "07"] },
  28: { nom_region: "Normandie", num_region: 28, academies: ["70"] },
  32: { nom_region: "Hauts-de-France", num_region: 32, academies: ["09", "20"] },
  44: { nom_region: "Grand Est", num_region: 44, academies: ["12", "15", "19"] },
  52: { nom_region: "Pays de la Loire", num_region: 52, academies: ["17"] },
  53: { nom_region: "Bretagne", num_region: 53, academies: ["14"] },
  75: { nom_region: "Nouvelle-Aquitaine", num_region: 75, academies: ["04", "13", "22"] },
  76: { nom_region: "Occitanie", num_region: 76, academies: ["11", "16"] },
  84: { nom_region: "Auvergne-Rhône-Alpes", num_region: 84, academies: ["10", "08", "06"] },
  93: { nom_region: "Provence-Alpes-Côte d'Azur", num_region: 93, academies: ["02", "23"] },
  94: { nom_region: "Corse", num_region: 94, academies: ["27"] },
};
